<?php

/*
S.E.E.R. - incl. Warrior module.
---------------------------------------------------------------------
System and Environment Effective Reports
-- version 2, codename: Brahma Bull
     ________________
   `/    \-'  '-/    \`
          \    /
          (\||/)

---------------------------------------------------------------------
 ... the http / web based front-end of mod_openopc, providing
     live HMI / reporting / and history functionality.
---------------------------------------------------------------------
---------------------------------------------------------------------
COPYRIGHT

 THE FOLLOWING 18 LINES MAY NOT BE REMOVED, but may be
     appended with additional contributor info.
 SEER 2
 Copyright (C) 2008 - 2013
 V. Spinelli for Sorrento Lactalis American Group
 Copyright (C) 2013 - 2014
 V. Spinelli for SpinelliCreations
 Copyright (C) 2014
 V. Spinelli for Harper International, Corp.
 Copyright (C) 2016
 V. Spinelli and J. Trembley for RS Automation, LLC.
 This program comes with ABSOLUTELY NO WARRANTY;
 As this program is based on [and has dependancies]
 the content of GPL and LGPL works, GPL is preserved (AGPL)
 This is open software, released under GNU AGPL v3,
 and you are welcome to redistribute it, with this
 tag in tact.
 A copy of the AGPL should be included with this work.
 If you did not receive a copy, see...
 http://www.gnu.org/licenses/agpl-3.0.txt
---------------------------------------------------------------------
---------------------------------------------------------------------
CONTACT		
		Author			V. Spinelli
				Email:	Vince@SpinelliCreations.com
				Site:	http://spinellicreations.com
				Handle:	PoweredByDodgeV8

		Copyright Holder	Sorrento Lactalis American Group
				Email:	http://www.sorrentocheese.com/about/contact.html
				Site:	http://www.sorrentolactalis.com

					SpinelliCreations
				Email:	Admin@SpinelliCreations.com
				Site:	http://www.spinellicreations.com

					Harper International, Corp.
				Email:	info@harperintl.com
				Site:	http://www.harperintl.com
					
					RS Automation, LLC.
				Email:	RickS@rsautomation.net
				Site:	http://www.rsautomation.net
---------------------------------------------------------------------
S.E.E.R. MODEL FUNCTIONS FILE (WARRIOR)
-- MODEL SUBROUTINES (FUNCTION BY FORM, SUBROUTINE BY EXECUTION)
---------------------------------------------------------------------
*/

	/* FILE SYSTEM NOTE */
	/* ---------------- */
	/* NOTE
	With regard to directory structure for UNIX versus WIN systems,
	S.E.E.R.'s implementation in PHP is operating system agnostic.
	Whether on WIN or UNIX, the syntax is the same.  For example...
	-- PHP call to folder... /my_folder/cheese
	-- will reference WIN folder... C:\my_folder\cheese
	-- will reference UNIX folder... /my_folder/cheese
	We rock the party that rocks the party.
	*/

/* POLL JOBS */
/* -- poll jobs from database and return array and formfill contents */
function model_WARRIOR_poll_job ()
{
	/* CALL THIS FUNCTION WITH... */
	/* list($WARRIOR_JOB_COUNT,$WARRIOR_JOB,$WARRIOR_FORMFILL_JOB_PLCSAFE_NUMBER) = model_WARRIOR_poll_job(); */

	/* GLOBALIZE VARIABLES */
	/*	-- SEER */
	global $seer_USERACTIVE;

	/*	-- MODEL SPECIFIC */
	global $WARRIOR_mysql_mod_openopc_TABLENAME_JOB;

	/* EXECUTE */
	if ( $seer_USERACTIVE == "YES" ) {
		/* POLL ALL JOB NUMBERS */
		$mysql_mod_openopc_query = "SELECT * FROM ".$WARRIOR_mysql_mod_openopc_TABLENAME_JOB." ORDER BY JOB_NUMBER ASC";
		list($mysql_mod_openopc_query_result,$mysql_mod_openopc_num_rows) = core_mysql_mod_openopc_query_shell($mysql_mod_openopc_query);
		/* BUILD AN ARRAY OF JOB NUMBERS */
		$WARRIOR_JOB_COUNT = 0;
		while ( $mysql_mod_openopc_query_row = mysqli_fetch_assoc($mysql_mod_openopc_query_result)) {
			/* PULL IN DATA */
			$mysql_mod_openopc_JOB_NUMBER = $mysql_mod_openopc_query_row['JOB_NUMBER'];
			$mysql_mod_openopc_JOB_DESCRIPTION = $mysql_mod_openopc_query_row['JOB_DESCRIPTION'];
			$mysql_mod_openopc_JOB_PLCSAFE_NUMBER = $mysql_mod_openopc_query_row['JOB_PLCSAFE_NUMBER'];
			/* ADD TO MULTIDIMENSIONAL ARRAY */
			$WARRIOR_JOB_COUNT = $WARRIOR_JOB_COUNT + 1;
			$WARRIOR_JOB['NUMBER'][$WARRIOR_JOB_COUNT] = $mysql_mod_openopc_JOB_NUMBER;
			$WARRIOR_JOB['DESCRIPTION'][$WARRIOR_JOB_COUNT] = $mysql_mod_openopc_JOB_DESCRIPTION;
			$WARRIOR_JOB['PLCSAFE_NUMBER'][$WARRIOR_JOB_COUNT] = $mysql_mod_openopc_JOB_PLCSAFE_NUMBER;
		}
		/* BUILD A FORMFILL OF JOB NUMBERS */
		$WARRIOR_FORMFILL_JOB_PLCSAFE_NUMBER = "";
		$WARRIOR_JOB_COUNT_CYCLE = 1;
		while ( $WARRIOR_JOB_COUNT_CYCLE <= $WARRIOR_JOB_COUNT) {
			$WARRIOR_FORMFILL_JOB_PLCSAFE_NUMBER = $WARRIOR_FORMFILL_JOB_PLCSAFE_NUMBER."<OPTION VALUE='".$WARRIOR_JOB['PLCSAFE_NUMBER'][$WARRIOR_JOB_COUNT_CYCLE]."'>".$WARRIOR_JOB['NUMBER'][$WARRIOR_JOB_COUNT_CYCLE]." - ".$WARRIOR_JOB['DESCRIPTION'][$WARRIOR_JOB_COUNT_CYCLE];
			$WARRIOR_JOB_COUNT_CYCLE = $WARRIOR_JOB_COUNT_CYCLE + 1;
		}
	} else {
		/* no action necessary */
	}

	/* RETURN VALUES */
	return array($WARRIOR_JOB_COUNT,$WARRIOR_JOB,$WARRIOR_FORMFILL_JOB_PLCSAFE_NUMBER);
}

/* CSV EXPORT ZERO - CSV and CSV2 */
/* -- REPORT 2 */
function model_WARRIOR_csv_and_csv2_zero_r2 ()
{
	/* CALL THIS FUNCTION WITH */
	/* model_WARRIOR_csv_and_csv2_zero_r2(); */

	/* GLOBALIZE VARIABLES */
	/*	-- SEER */
	global $seer_EXPORT_CONTENT,$seer_EXPORT_CONTENT2,$seer_CSV_DELINEATION,$seer_CSV_ENDOFLINE_HOLDING;

	/*	-- CSV */
	global $multilang_WARRIOR_81,$multilang_WARRIOR_61,$multilang_WARRIOR_60,$multilang_WARRIOR_62,$multilang_WARRIOR_64,$multilang_WARRIOR_63,$multilang_WARRIOR_50,$WARRIOR_UM_PACKAGE_UNIT,$multilang_WARRIOR_51,$WARRIOR_UM_PACKAGE_UNIT_MASS,$multilang_WARRIOR_104,$multilang_WARRIOR_55,$multilang_WARRIOR_101,$multilang_WARRIOR_58,$multilang_WARRIOR_57;

	/*	-- CSV2 */
	global $multilang_WARRIOR_81,$multilang_WARRIOR_106,$multilang_WARRIOR_107,$multilang_WARRIOR_94,$multilang_WARRIOR_53,$multilang_WARRIOR_113,$multilang_WARRIOR_28;

	/* EXECUTE*/
	/* -- ZERO OUT CSV FOR EXPORT */
	/* -- -- MACHINE, AVAILABILITY[UM], PERFORMANCE[UM], OEE[UM], LOADING[UM], TEEP[UM], GROSS THROUGHPUT UNIT[UM], GROSS THROUGHPUT MASS[UM], TIME PERIOD[UM], RUNTIME[UM], DOWN TIME[UM], NOT SCHEDULED[UM] */
	$seer_EXPORT_CONTENT = "-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_ENDOFLINE_HOLDING.$multilang_WARRIOR_81.$seer_CSV_DELINEATION.$multilang_WARRIOR_61."[%]".$seer_CSV_DELINEATION.$multilang_WARRIOR_60."[%]".$seer_CSV_DELINEATION.$multilang_WARRIOR_62."[%]".$seer_CSV_DELINEATION.$multilang_WARRIOR_64."[%]".$seer_CSV_DELINEATION.$multilang_WARRIOR_63."[%]".$seer_CSV_DELINEATION.$multilang_WARRIOR_50."[".$WARRIOR_UM_PACKAGE_UNIT."]".$seer_CSV_DELINEATION.$multilang_WARRIOR_51."[".$WARRIOR_UM_PACKAGE_UNIT_MASS."]".$seer_CSV_DELINEATION.$multilang_WARRIOR_104."[".$multilang_WARRIOR_101."]".$seer_CSV_DELINEATION.$multilang_WARRIOR_55."[".$multilang_WARRIOR_101."]".$seer_CSV_DELINEATION.$multilang_WARRIOR_58."[".$multilang_WARRIOR_101."]".$seer_CSV_DELINEATION.$multilang_WARRIOR_57."[".$multilang_WARRIOR_101."]".$seer_CSV_DELINEATION.$seer_CSV_ENDOFLINE_HOLDING."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_ENDOFLINE_HOLDING;

	/* -- ZERO OUT CSV 2 FOR EXPORT */
	/* -- -- MACHINE, START, END, DURATION[UM], ALARM, CORRECTIVE ACTION + 6 FILLER */
	$seer_EXPORT_CONTENT2 = $multilang_WARRIOR_81.$seer_CSV_DELINEATION.$multilang_WARRIOR_106.$seer_CSV_DELINEATION.$multilang_WARRIOR_107.$seer_CSV_DELINEATION.$multilang_WARRIOR_94."[".$multilang_WARRIOR_53."]".$seer_CSV_DELINEATION.$multilang_WARRIOR_113.$seer_CSV_DELINEATION.$multilang_WARRIOR_28.$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_ENDOFLINE_HOLDING;
}

/* CSV EXPORT BORDER - 12 COLUMN */
/* -- REPORT 2 */
function model_WARRIOR_csv_export_r2_border_12_column ()
{
	/* CALL THIS FUNCTION WITH */
	/* model_WARRIOR_csv_export_r2_border_12_column(); */

	/* GLOBALIZE VARIABLES */
	/*	-- SEER */
	global $seer_EXPORT_CONTENT,$seer_CSV_DELINEATION,$seer_CSV_ENDOFLINE_HOLDING;

	/* EXECUTE*/
	$seer_EXPORT_CONTENT = $seer_EXPORT_CONTENT."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_ENDOFLINE_HOLDING;
}

/* CSV2 EXPORT BORDER - 12 COLUMN */
/* -- REPORT 2 */
function model_WARRIOR_csv2_export_r2_border_12_column ()
{
	/* CALL THIS FUNCTION WITH */
	/* model_WARRIOR_csv2_export_r2_border_12_column(); */

	/* GLOBALIZE VARIABLES */
	/*	-- SEER */
	global $seer_EXPORT_CONTENT2,$seer_CSV_DELINEATION,$seer_CSV_ENDOFLINE_HOLDING;

	/* EXECUTE*/
	$seer_EXPORT_CONTENT2 = $seer_EXPORT_CONTENT2."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_DELINEATION."-----".$seer_CSV_ENDOFLINE_HOLDING;
}

/* CONVERT STATE TO 'FRIENDLY' VALUE AND HIGHLIGHT WITH COLOR */
function model_WARRIOR_friendly_state_with_highlight_color ($post_CURRENT_STATE)
{
	/* CALL THIS FUNCTION WITH... */
	/* list($WARRIOR_RESULT_CURRENT_STATE_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE,$WARRIOR_FLAG_MAINT_MODE,$WARRIOR_FLAG_CORRECTIVE_ACTION) = model_WARRIOR_friendly_state_with_highlight_color($post_CURRENT_STATE); */

	/* GLOBALIZE VARIABLES */
	/*	-- MODEL SPECIFIC */
	global $WARRIOR_STATE;

	/* EXECUTE */
	$WARRIOR_FLAG_CORRECTIVE_ACTION = 0;
	$WARRIOR_FLAG_MAINT_MODE = 0;
	$WARRIOR_RESULT_CURRENT_STATE_FRIENDLYNAME = $WARRIOR_STATE[$post_CURRENT_STATE];
	if ( $post_CURRENT_STATE <= 1 ) {
		/* MACHINE DOWN FLAG AS RED */
		$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE = "BGCOLOR='#FF8866'";
		$WARRIOR_FLAG_CORRECTIVE_ACTION = 1;
	} else {
		if ( $post_CURRENT_STATE == 2 ) {
			/* MACHINE RUNNING IN MAINT MODE FLAG AS YELLOW */
			$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE = "BGCOLOR='#FFF380'";
			$WARRIOR_FLAG_MAINT_MODE = 1;
		} else {
			if ( $post_CURRENT_STATE == 3 ) {
				/* MACHINE RUNNING WITH FAULT FLAG AS YELLOW */
				$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE = "BGCOLOR='#FFF380'";
			} else {
				if ( $post_CURRENT_STATE == 4 ) {
					/* MACHINE RUNNING NO FAULTS FLAG AS GREEN */
					$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE = "BGCOLOR='#CCFF66'";
				} else {
					/* pass */
				}
			}
		}
	}

	/* RETURN VALUES */
	return array($WARRIOR_RESULT_CURRENT_STATE_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE,$WARRIOR_FLAG_MAINT_MODE,$WARRIOR_FLAG_CORRECTIVE_ACTION);
}

/* CONVERT ALARM TO 'FRIENDLY' VALUE WITH BACKGROUND HIGHLIGHT COLOR */
function model_WARRIOR_friendly_alarm_with_highlight_color ($post_CURRENT_ALARM)
{
	/* CALL THIS FUNCTION WITH... */
	/* list($WARRIOR_RESULT_CURRENT_ALARM_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_ALARM) = model_WARRIOR_friendly_alarm_with_highlight_color($post_CURRENT_ALARM); */

	/* GLOBALIZE VARIABLES */
	/*	-- MODEL SPECIFIC */
	global $WARRIOR_ALARM;

	/* 	-- APACHE */
	global $WARRIOR_FLAG_MAINT_MODE,$apache_REPORT_ROW_BGCOLOR;

	/* EXECUTE */
	$WARRIOR_RESULT_CURRENT_ALARM_FRIENDLYNAME = $WARRIOR_ALARM[$post_CURRENT_ALARM];
	if ( $WARRIOR_FLAG_MAINT_MODE == 1 ) {
		/* MAINT MODE, FLAG AS BLUE */
		$apache_REPORT_ROW_BGCOLOR_CURRENT_ALARM = "BGCOLOR='#C4E4FD'";
	} else {
		if ( $post_CURRENT_ALARM > 1 ) {
			/* ALARM ACTIVE, FLAG AS RED */
			$apache_REPORT_ROW_BGCOLOR_CURRENT_ALARM = "BGCOLOR='#FF8866'";
		} else {
			$apache_REPORT_ROW_BGCOLOR_CURRENT_ALARM = $apache_REPORT_ROW_BGCOLOR;
		}
	}

	/* RETURN VALUES */
	return array($WARRIOR_RESULT_CURRENT_ALARM_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_ALARM);
}

/* CONVERT CORRECTIVE ACTION TO 'FRIENDLY' VALUE */
function model_WARRIOR_friendly_action ($post_CURRENT_ACTION,$post_CURRENT_STATE,$post_FLAG_MAINT_MODE,$post_ROW_BGCOLOR_CURRENT_STATE)
{
	/* CALL THIS FUNCTION WITH... */
	/* list($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE) = model_WARRIOR_friendly_action($post_CURRENT_ACTION,$post_CURRENT_STATE,$post_FLAG_MAINT_MODE,$post_ROW_BGCOLOR_CURRENT_STATE); */

	/* GLOBALIZE VARIABLES */
	/*	-- MODEL SPECIFIC */
	global $WARRIOR_ACTION;

	/* EXECUTE */
	$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION_FRIENDLYNAME = $WARRIOR_ACTION[$post_CURRENT_ACTION];
	$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE = $post_ROW_BGCOLOR_CURRENT_STATE;
	if ( $post_FLAG_MAINT_MODE == 1 ) {
		/* MAINT MODE, NO FLAG */
		/* pass */
	} else {
		if ( ($post_CURRENT_ACTION >= 2) && ($post_CURRENT_ACTION <= 3) && ($post_CURRENT_STATE < 3) ) {
			/* WHEN SCHEDULED DOWN OR CLEANING, WE'LL JUST FLAG AS YELLOW STATE ONLY */
			/* -- SAME FOR IF OPERATORS ARE ON LUNCH BREAK */
			$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE = "BGCOLOR='#FFF380'";
		} else {
			/* pass */
		}
	}

	/* RETURN VALUES */
	return array($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE);
}

/* CONVERT OPERATOR ID TO 'FRIENDLY' VALUE */
function model_WARRIOR_friendly_operator ($post_CURRENT_OPERATOR)
{
	/* CALL THIS FUNCTION WITH... */
	/* $WARRIOR_RESULT_CURRENT_OPERATOR_FRIENDLYNAME = model_WARRIOR_friendly_operator($post_CURRENT_OPERATOR); */

	/* GLOBALIZE VARIABLES */
	/*	-- LANGUAGE */
	global $multilang_STATIC_NONE;

	/* EXECUTE */
	if ($post_CURRENT_OPERATOR == 0) {
		$WARRIOR_RESULT_CURRENT_OPERATOR_FRIENDLYNAME = $multilang_STATIC_NONE;
	} else {
		$mysql_seer_query = "REALNAME";
		$mysql_seer_query = "SELECT ".$mysql_seer_query." FROM access WHERE UID LIKE '".$post_CURRENT_OPERATOR."'";
		list($mysql_seer_query_result,$mysql_seer_num_rows) = core_mysql_seer_query_shell($mysql_seer_query);
		while ( $mysql_seer_query_row = mysqli_fetch_assoc($mysql_seer_query_result) ) {
			$WARRIOR_RESULT_CURRENT_OPERATOR_FRIENDLYNAME = $mysql_seer_query_row['REALNAME'];
		}
	}

	/* RETURN VALUES */
	return $WARRIOR_RESULT_CURRENT_OPERATOR_FRIENDLYNAME;
}

/* CONVERT JOB NUMBER ID TO 'FRIENDLY' VALUE */
function model_WARRIOR_friendly_jobnumber ($post_CURRENT_JOB_NUMBER,$post_USE_NON_PLCSAFE_NUMBER="SAFE")
{
	/* CALL THIS FUNCTION WITH... */
	/* $WARRIOR_RESULT_CURRENT_JOB_NUMBER_FRIENDLYNAME = model_WARRIOR_friendly_jobnumber($post_CURRENT_JOB_NUMBER); */

	/* GLOBALIZE VARIABLES */
	/*	-- LANGUAGE */
	global $multilang_STATIC_NONE;

	/*	-- MODEL SPECIFIC */
	global $WARRIOR_mysql_mod_openopc_TABLENAME_JOB;

	/*	-- WARRIOR */
	global $WARRIOR_RESULT_CURRENT_JOB_NUMBER_NONFRIENDLYNAME;

	/* EXECUTE */
	if ($post_CURRENT_JOB_NUMBER == 0) {
		$WARRIOR_RESULT_CURRENT_JOB_NUMBER_FRIENDLYNAME = $multilang_STATIC_NONE;
		$WARRIOR_RESULT_CURRENT_JOB_NUMBER_NONFRIENDLYNAME = 0;
	} else {
		$mysql_mod_openopc_query_2 = "*";
		if ($post_USE_NON_PLCSAFE_NUMBER == 'UNSAFE') {
			$mysql_mod_openopc_query_2 = "SELECT ".$mysql_mod_openopc_query_2." FROM ".$WARRIOR_mysql_mod_openopc_TABLENAME_JOB." WHERE JOB_NUMBER  LIKE '".$post_CURRENT_JOB_NUMBER."'";
		} else {
			$mysql_mod_openopc_query_2 = "SELECT ".$mysql_mod_openopc_query_2." FROM ".$WARRIOR_mysql_mod_openopc_TABLENAME_JOB." WHERE JOB_PLCSAFE_NUMBER  LIKE '".$post_CURRENT_JOB_NUMBER."'";
		}
		list($mysql_mod_openopc_query_result_2,$mysql_mod_openopc_num_rows) = core_mysql_mod_openopc_query_shell($mysql_mod_openopc_query_2);
		while ( $mysql_mod_openopc_query_row_2 = mysqli_fetch_assoc($mysql_mod_openopc_query_result_2) ) {
			$WARRIOR_RESULT_CURRENT_JOB_NUMBER_FRIENDLYNAME = $mysql_mod_openopc_query_row_2['JOB_NUMBER']." - ".$mysql_mod_openopc_query_row_2['JOB_DESCRIPTION'];
			$WARRIOR_RESULT_CURRENT_JOB_NUMBER_NONFRIENDLYNAME = $mysql_mod_openopc_query_row_2['JOB_NUMBER'];
		}
	}

	/* RETURN VALUES */
	return $WARRIOR_RESULT_CURRENT_JOB_NUMBER_FRIENDLYNAME;
}

/* HMI REPORT BODY - FIRST RUN SPECIFIC */
function model_WARRIOR_hmi_report_body_first_run ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_hmi_report_body_first_run(); */

	/* GLOBALIZE VARIABLES */
	/* 	-- MODEL SPECIFIC */
	global $WARRIOR_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_ALARM,$WARRIOR_PACKAGE,$WARRIOR_PACKAGE_UNIT_COUNT,$WARRIOR_PACKAGE_UNIT_MASS,$WARRIOR_UM_PACKAGE_UNIT,$WARRIOR_UM_PACKAGE_UNIT_MASS;

	/*	-- HMI0 CHECKS */
	global $WARRIOR_RESULT_CURRENT_STATE_MAINTAIN_FOR_CHECK, $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER_MAINTAIN_FOR_CHECK, $WARRIOR_RESULT_CURRENT_JOB_NUMBER_MAINTAIN_FOR_CHECK;

	/*	-- APACHE */
	global $apache_REPORT_FRESHTIME,$WARRIOR_RESULT_FIRSTRUN;

	/*	-- MYSQL QUERY ROW RESULTS */
	global $WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_MASS,$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_COUNT,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS_FRIENDLYNAME,$seer_MACHINE_TO_DISPLAY_FRIENDLYNAME,$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER_FRIENDLYNAME,$mysql_mod_openopc_query_row,$WARRIOR_RESULT_CURRENT_DATESTAMP,$WARRIOR_RESULT_CURRENT_OPERATOR,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_RESULT_CURRENT_ALARM,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS,$WARRIOR_RESULT_TEST_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE,$WARRIOR_RESULT_CURRENT_CYCLES_END,$WARRIOR_RESULT_CURRENT_JOB_NUMBER;

	/*	-- MYSQL CHECKSTOPS BASED ON QUERY ROW RESULTS */
	global $WARRIOR_CHECKSTOP_JOB_NUMBER,$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER,$WARRIOR_CHECKSTOP_CORRECTIVE_ACTION,$WARRIOR_CHECKSTOP_ALARM,$WARRIOR_CHECKSTOP_STATE,$WARRIOR_CHECKSTOP_DATESTAMP_START,$WARRIOR_CHECKSTOP_DATESTAMP_END,$WARRIOR_CHECKSTOP_CYCLES,$WARRIOR_RESULT_CURRENT_PACKAGES_END,$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_END,$WARRIOR_RESULT_CURRENT_MASS_END,$WARRIOR_RESULT_CURRENT_JOB_NUMBER_FRIENDLYNAME,$WARRIOR_RESULT_CURRENT_OPERATOR_FRIENDLYNAME,$WARRIOR_RESULT_CURRENT_ALARM_FRIENDLYNAME, $WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION_FRIENDLYNAME, $WARRIOR_RESULT_CURRENT_STATE_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE,$WARRIOR_FLAG_MAINT_MODE,$WARRIOR_FLAG_CORRECTIVE_ACTION;

	/* EXECUTE */
	/* -- SPECIAL BEHAVIOR FOR THE FIRST RUN */
	/* -- ZERO DOWNTIME ACTIVITY */
	$WARRIOR_DOWNTIME_ACTIVE = 0;
	$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE = 0;
	/* -- QUERY RESULTS */
	$WARRIOR_RESULT_CURRENT_DATESTAMP = $mysql_mod_openopc_query_row['DATESTAMP'];
	$WARRIOR_RESULT_CURRENT_OPERATOR = $mysql_mod_openopc_query_row['OPERATOR'];
	$WARRIOR_RESULT_CURRENT_STATE = $mysql_mod_openopc_query_row['STATE'];
	$WARRIOR_RESULT_CURRENT_ALARM = $mysql_mod_openopc_query_row['ALARM'];
	$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION = $mysql_mod_openopc_query_row['CORRECTIVE_ACTION'];
	$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS = $mysql_mod_openopc_query_row['PACKAGE_CLASS'];
	$WARRIOR_RESULT_TEST_PACKAGE_CLASS = $mysql_mod_openopc_query_row['PACKAGE_CLASS'];
	$WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE = $mysql_mod_openopc_query_row['PACKAGES_PER_CYCLE'];
	$WARRIOR_RESULT_CURRENT_CYCLES_END = $mysql_mod_openopc_query_row['CYCLES'];
	$WARRIOR_RESULT_CURRENT_JOB_NUMBER = $mysql_mod_openopc_query_row['JOB_NUMBER'];

	/* HMI0 CHECKS */
	$WARRIOR_RESULT_CURRENT_STATE_MAINTAIN_FOR_CHECK = $WARRIOR_RESULT_CURRENT_STATE;
	$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER_MAINTAIN_FOR_CHECK = $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER_FRIENDLYNAME;
	$WARRIOR_RESULT_CURRENT_JOB_NUMBER_MAINTAIN_FOR_CHECK = $WARRIOR_RESULT_CURRENT_JOB_NUMBER;

	/* -- DATA FRESH TIME */
	if ($WARRIOR_RESULT_CURRENT_DATESTAMP > $apache_REPORT_FRESHTIME) {
		$apache_REPORT_FRESHTIME = $WARRIOR_RESULT_CURRENT_DATESTAMP;
	} else {
		/* pass */
	}

	/* -- UPDATE CHECKSTOPS */
	$WARRIOR_CHECKSTOP_JOB_NUMBER = $WARRIOR_RESULT_CURRENT_JOB_NUMBER;
	$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER = $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER_FRIENDLYNAME;
	$WARRIOR_CHECKSTOP_CORRECTIVE_ACTION = $WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION;
	$WARRIOR_CHECKSTOP_ALARM = $WARRIOR_RESULT_CURRENT_ALARM;
	$WARRIOR_CHECKSTOP_STATE = $WARRIOR_RESULT_CURRENT_STATE;
	$WARRIOR_CHECKSTOP_DATESTAMP_END = $WARRIOR_RESULT_CURRENT_DATESTAMP;
	$WARRIOR_CHECKSTOP_DATESTAMP_START = $WARRIOR_RESULT_CURRENT_DATESTAMP;
	$WARRIOR_CHECKSTOP_CYCLES = $WARRIOR_RESULT_CURRENT_CYCLES_END;

	/* -- CONVERT TO FRIENDLY NAMES */
	/* -- -- STATE */
	/* -------- */
	list($WARRIOR_RESULT_CURRENT_STATE_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE,$WARRIOR_FLAG_MAINT_MODE,$WARRIOR_FLAG_CORRECTIVE_ACTION) = model_WARRIOR_friendly_state_with_highlight_color($WARRIOR_RESULT_CURRENT_STATE);
	/* -- CURRENT ALARM */
	/* ---------------- */
	$WARRIOR_RESULT_CURRENT_ALARM_FRIENDLYNAME = $WARRIOR_ALARM[$WARRIOR_RESULT_CURRENT_ALARM];
	/* -- -- CURRENT CORRECTIVE ACTION */
	/* ---------------------------- */
	list($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION_FRIENDLYNAME,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE) = model_WARRIOR_friendly_action($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_FLAG_MAINT_MODE,$apache_REPORT_ROW_BGCOLOR_CURRENT_STATE);
	/* -- CURRENT PACKAGE CLASS */
	/* ------------------------ */
	$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS_FRIENDLYNAME = $WARRIOR_PACKAGE[$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS];
	$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_COUNT = $WARRIOR_PACKAGE_UNIT_COUNT[$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS];
	$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_MASS = $WARRIOR_PACKAGE_UNIT_MASS[$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS];
	/* -- -- CURRENT PACKAGES PER CYCLE */
	/* ----------------------------- */
	$WARRIOR_RESULT_CURRENT_PACKAGES_END = $WARRIOR_RESULT_CURRENT_CYCLES_END * $WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE;
	$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_END = $WARRIOR_RESULT_CURRENT_PACKAGES_END * $WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_COUNT;
	$WARRIOR_RESULT_CURRENT_MASS_END = varcharTOnumeric2($WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_END * $WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_MASS);
	/* -- -- CURRENT OPERATOR */
	/* ------------------- */
	$WARRIOR_RESULT_CURRENT_OPERATOR_FRIENDLYNAME = model_WARRIOR_friendly_operator($WARRIOR_RESULT_CURRENT_OPERATOR);
	/* -- -- CURRENT JOB NUMBER */
	/* --------------------- */
	$WARRIOR_RESULT_CURRENT_JOB_NUMBER_FRIENDLYNAME = model_WARRIOR_friendly_jobnumber($WARRIOR_RESULT_CURRENT_JOB_NUMBER);

	/* -- DEACTIVE FIRST RUN */
	$WARRIOR_RESULT_FIRSTRUN = 0;
}

/* HMI REPORT BODY - SUBSEQUENT RUN SPECIFIC */
function model_WARRIOR_hmi_report_body_subsequent_run ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_hmi_report_body_subsequent_run(); */

	/* GLOBALIZE VARIABLES */
	/*	-- MYSQL QUERY ROW RESULTS */
	global	$mysql_mod_openopc_query_row,$WARRIOR_RESULT_CURRENT_DATESTAMP_START,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_RESULT_CURRENT_ALARM,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_RESULT_CURRENT_CYCLES_START,$WARRIOR_RESULT_CURRENT_JOB_NUMBER,$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER,$WARRIOR_RESULT_TEST_PACKAGE_CLASS;

	/* EXECUTE */
	$WARRIOR_RESULT_CURRENT_DATESTAMP_START = $mysql_mod_openopc_query_row['DATESTAMP'];
	$WARRIOR_RESULT_CURRENT_STATE = $mysql_mod_openopc_query_row['STATE'];
	$WARRIOR_RESULT_CURRENT_ALARM = $mysql_mod_openopc_query_row['ALARM'];
	$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION = $mysql_mod_openopc_query_row['CORRECTIVE_ACTION'];
	$WARRIOR_RESULT_CURRENT_CYCLES_START = $mysql_mod_openopc_query_row['CYCLES'];
	$WARRIOR_RESULT_CURRENT_JOB_NUMBER = $mysql_mod_openopc_query_row['JOB_NUMBER'];
	$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER = $mysql_mod_openopc_query_row['SCHEDULE_NUMBER'];
	$WARRIOR_RESULT_TEST_PACKAGE_CLASS = $mysql_mod_openopc_query_row['PACKAGE_CLASS'];

	/* -- ASSESS CONDITION OF DOWNTIME */
	model_WARRIOR_assess_condition_of_downtime();

	/* -- UPDATE DOWNTIME CHECKSTOPS */
	model_WARRIOR_update_downtime_checkstops();
		
	/* -- UPDATE DOWNTIME TOTALS */
	model_WARRIOR_update_downtime_totals();

	/* -- SCRUTINIZE HISTORY */
	model_WARRIOR_scrutinize_history();
}

/* HMI REPORT BODY - PREP */
function model_WARRIOR_hmi_report_body_prep ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_hmi_report_body_prep(); */

	/* GLOBALIZE VARIABLES */
	/*	-- ALL */
	global $WARRIOR_RESULT_FIRSTRUN,$WARRIOR_EXAMINE_RECENT_HISTORY,$WARRIOR_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_TOTAL_DOWNTIME_UNIXTIME,$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME,$WARRIOR_PROCESS_DOWNTIME_ACTIVE,$WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME,$WARRIOR_RESULT_CURRENT_DATESTAMP,$WARRIOR_RESULT_CURRENT_OPERATOR,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_RESULT_CURRENT_ALARM,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE,$WARRIOR_RESULT_CURRENT_CYCLES_END,$WARRIOR_RESULT_CURRENT_JOB_NUMBER;

	/* EXECUTE */
	/* -- ACTIVATE FIRST RUN and HISTORY */
	$WARRIOR_RESULT_FIRSTRUN = 1;
	$WARRIOR_EXAMINE_RECENT_HISTORY = 1;

	/* -- START UP THE RUNTIME COUNTER */
	$WARRIOR_DOWNTIME_ACTIVE = 0;
	$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE = 0;
	$WARRIOR_TOTAL_DOWNTIME_UNIXTIME = 0;
	$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME = 0;
	$WARRIOR_PROCESS_DOWNTIME_ACTIVE = 0;
	$WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE = 0;
	$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME = 0;
	$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME = 0;

	/* -- GRAB RESULTS AND DUMP INTO ARRAY */
	$WARRIOR_RESULT_CURRENT_DATESTAMP = "";
	$WARRIOR_RESULT_CURRENT_OPERATOR = "";
	$WARRIOR_RESULT_CURRENT_STATE = "";
	$WARRIOR_RESULT_CURRENT_ALARM = "";
	$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION = "";
	$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS = "";
	$WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE = "";
	$WARRIOR_RESULT_CURRENT_CYCLES_END = 0;
	$WARRIOR_RESULT_CURRENT_JOB_NUMBER = "";
}

/* HMI REPORT BODY - SUMMATION */
function model_WARRIOR_hmi_report_body_summation ($post_BAR_GRAPH_DIMENSION_PIXELS="100")
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_hmi_report_body_summation($post_BAR_GRAPH_DIMENSION_PIXELS); */

	/* GLOBALIZE VARIABLES */
	/*	-- ALL */
	global $WARRIOR_TOTAL_CYCLES,$WARRIOR_RESULT_CURRENT_CYCLES_END,$WARRIOR_CHECKSTOP_CYCLES,$WARRIOR_TOTAL_PACKAGES,$WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE,$WARRIOR_TOTAL_UNITS,$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_COUNT,$WARRIOR_TOTAL_MASS,$WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_MASS,$WARRIOR_CHECKSTOP_DATESTAMP_START,$WARRIOR_CHECKSTOP_DATESTAMP_END,$WARRIOR_TOTAL_DURATION_READABLE,$WARRIOR_TOTAL_DURATION_UNIXTIME,$WARRIOR_TOTAL_DURATION_MINUTES,$WARRIOR_TOTAL_DURATION_MINUTES,$WARRIOR_TOTAL_DURATION_HOURS,$WARRIOR_TOTAL_DURATION_HOURS,$WARRIOR_TOTAL_DOWNTIME_UNIXTIME,$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME,$WARRIOR_TOTAL_DOWNTIME_MINUTES,$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES,$WARRIOR_TOTAL_RUN_MINUTES,$WARRIOR_BAR_GRAPH_RUN_MINUTES,$WARRIOR_BAR_GRAPH_SCHEDULED_DOWNTIME_MINUTES,$WARRIOR_BAR_GRAPH_DOWNTIME_MINUTES,$WARRIOR_PERFORMANCE_RATE_UNITS,$WARRIOR_TOTAL_UNITS,$WARRIOR_PERFORMANCE_RATE_MASS,$WARRIOR_TOTAL_MASS,$WARRIOR_PERFORMANCE_OEE,$WARRIOR_PERFORMANCE_RATE_UNITS,$WARRIOR_PACKAGE_TARGET_RATE,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS,$WARRIOR_AVAILABILITY_OEE,$WARRIOR_AVAILABILITY_RATE_UNITS,$WARRIOR_AVAILABILITY_RATE_MASS,$WARRIOR_LOADING_TEEP,$WARRIOR_OEE,$WARRIOR_TEEP,$WARRIOR_RECENT_WINDOW_SIZE_IN_HOURS,$seer_HMISQLSEARCHMINIMUMTIMEFRAME_WARRIOR,$WARRIOR_IDEAL_HOUR_UNIT,$WARRIOR_PACKAGE_TARGET_RATE,$WARRIOR_IDEAL_HOUR_MASS,$WARRIOR_PACKAGE_UNIT_MASS;

	/* EXECUTE */
	/* -- TOTALIZE */
	$WARRIOR_TOTAL_CYCLES = $WARRIOR_RESULT_CURRENT_CYCLES_END - $WARRIOR_CHECKSTOP_CYCLES;
	$WARRIOR_TOTAL_PACKAGES = $WARRIOR_TOTAL_CYCLES * $WARRIOR_RESULT_CURRENT_PACKAGES_PER_CYCLE;
	$WARRIOR_TOTAL_UNITS = $WARRIOR_TOTAL_PACKAGES * $WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_COUNT;
	$WARRIOR_TOTAL_MASS = varcharTOnumeric2($WARRIOR_TOTAL_UNITS * $WARRIOR_RESULT_CURRENT_PACKAGE_UNIT_MASS);

	/* -- DURATION of RUN (THUS FAR, AND REMEMBER, WE ONLY LOOK AT [TIME WINDOW] SO */
	/* -- IT IS BETTER STATED AS 'DURATION OF RUN WITHIN TIME WINDOW' */
	$apache_function_STARTTIME = $WARRIOR_CHECKSTOP_DATESTAMP_START;
	$apache_function_ENDTIME = $WARRIOR_CHECKSTOP_DATESTAMP_END;
	list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
	$WARRIOR_TOTAL_DURATION_READABLE = $apache_function_DURATION_FINAL;
	$WARRIOR_TOTAL_DURATION_UNIXTIME = $apache_function_DURATION_UNIXTIME;
	$WARRIOR_TOTAL_DURATION_MINUTES = $WARRIOR_TOTAL_DURATION_UNIXTIME / 60;
	$WARRIOR_TOTAL_DURATION_MINUTES = varcharTOnumeric2($WARRIOR_TOTAL_DURATION_MINUTES, 0);
	$WARRIOR_TOTAL_DURATION_HOURS = $WARRIOR_TOTAL_DURATION_UNIXTIME / 360;
	$WARRIOR_TOTAL_DURATION_HOURS = varcharTOnumeric2($WARRIOR_TOTAL_DURATION_HOURS, 2);

	/* -- TOTALS FINALIZED */
	if (isset($WARRIOR_TOTAL_DOWNTIME_UNIXTIME)) {
		/* pass */
	} else {
		$WARRIOR_TOTAL_DOWNTIME_UNIXTIME = 0;
	}
	if (isset($WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME)) {
		/* pass */
	} else {
		$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME = 0;
	}
	$WARRIOR_TOTAL_DOWNTIME_MINUTES = $WARRIOR_TOTAL_DOWNTIME_UNIXTIME / 60;
	$WARRIOR_TOTAL_DOWNTIME_MINUTES = varcharTOnumeric2($WARRIOR_TOTAL_DOWNTIME_MINUTES, 0);
	$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES = $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME / 60;
	$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES = varcharTOnumeric2($WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES, 0);
	$WARRIOR_TOTAL_RUN_MINUTES = $WARRIOR_TOTAL_DURATION_MINUTES - ($WARRIOR_TOTAL_DOWNTIME_MINUTES + $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES);
	$WARRIOR_TOTAL_RUN_MINUTES = varcharTOnumeric2($WARRIOR_TOTAL_RUN_MINUTES, 0);

	/* -- BAR GRAPH FILL */
	$WARRIOR_BAR_GRAPH_RUN_MINUTES = core_display_horizontal_bar($post_BAR_GRAPH_DIMENSION_PIXELS,$WARRIOR_TOTAL_RUN_MINUTES,"0",$WARRIOR_TOTAL_DURATION_MINUTES);
	$WARRIOR_BAR_GRAPH_SCHEDULED_DOWNTIME_MINUTES = core_display_horizontal_bar($post_BAR_GRAPH_DIMENSION_PIXELS,$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES,"0",$WARRIOR_TOTAL_DURATION_MINUTES);
	$WARRIOR_BAR_GRAPH_DOWNTIME_MINUTES = core_display_horizontal_bar($post_BAR_GRAPH_DIMENSION_PIXELS,$WARRIOR_TOTAL_DOWNTIME_MINUTES,"0",$WARRIOR_TOTAL_DURATION_MINUTES);

	/* -- PERFORMANCE */
	if (is_numeric($WARRIOR_TOTAL_RUN_MINUTES) && ($WARRIOR_TOTAL_RUN_MINUTES > 0)) {
		$WARRIOR_PERFORMANCE_RATE_UNITS = varcharTOnumeric2(($WARRIOR_TOTAL_UNITS * 60 / $WARRIOR_TOTAL_RUN_MINUTES), 2);
		$WARRIOR_PERFORMANCE_RATE_MASS = varcharTOnumeric2(($WARRIOR_TOTAL_MASS * 60 / $WARRIOR_TOTAL_RUN_MINUTES));
	} else {
		$WARRIOR_PERFORMANCE_RATE_UNITS = 0;
		$WARRIOR_PERFORMANCE_RATE_MASS = 0;
	}
	$WARRIOR_PERFORMANCE_OEE = ($WARRIOR_PERFORMANCE_RATE_UNITS / $WARRIOR_PACKAGE_TARGET_RATE[$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS]) * 100;
	$WARRIOR_PERFORMANCE_OEE = varcharTOnumeric2($WARRIOR_PERFORMANCE_OEE, 2);
		
	/* -- AVAILABILITY */
	$WARRIOR_AVAILABILITY_OEE = ( $WARRIOR_TOTAL_RUN_MINUTES / ( $WARRIOR_TOTAL_DURATION_MINUTES - $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES ) ) * 100;
	$WARRIOR_AVAILABILITY_OEE = varcharTOnumeric2($WARRIOR_AVAILABILITY_OEE, 2);
	$WARRIOR_AVAILABILITY_RATE_UNITS = varcharTOnumeric2(($WARRIOR_TOTAL_UNITS * 60 / ($WARRIOR_TOTAL_RUN_MINUTES + $WARRIOR_TOTAL_DOWNTIME_MINUTES)), 2);
	$WARRIOR_AVAILABILITY_RATE_MASS = varcharTOnumeric2(($WARRIOR_TOTAL_MASS * 60 / ($WARRIOR_TOTAL_RUN_MINUTES + $WARRIOR_TOTAL_DOWNTIME_MINUTES)));

	/* -- LOADING */
	$WARRIOR_LOADING_TEEP = (( $WARRIOR_TOTAL_DURATION_MINUTES - $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_MINUTES ) / $WARRIOR_TOTAL_DURATION_MINUTES ) * 100;
	$WARRIOR_LOADING_TEEP = varcharTOnumeric2($WARRIOR_LOADING_TEEP, 2);

	/* -- OEE */
	$WARRIOR_OEE = ($WARRIOR_AVAILABILITY_OEE * $WARRIOR_PERFORMANCE_OEE) / 100;
	$WARRIOR_OEE = varcharTOnumeric2($WARRIOR_OEE, 2);

	/* -- TEEP */
	$WARRIOR_TEEP = ($WARRIOR_OEE * $WARRIOR_LOADING_TEEP) / 100;
	$WARRIOR_TEEP = varcharTOnumeric2($WARRIOR_TEEP, 2);

	/* -- RECENT WINDOW IN HOURS */
	$WARRIOR_RECENT_WINDOW_SIZE_IN_HOURS = varcharTOnumeric2(($seer_HMISQLSEARCHMINIMUMTIMEFRAME_WARRIOR / 60), 2);
	
	/* -- IDEALS */
	$WARRIOR_IDEAL_HOUR_UNIT = $WARRIOR_PACKAGE_TARGET_RATE[$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS];
	$WARRIOR_IDEAL_HOUR_UNIT = varcharTOnumeric2($WARRIOR_IDEAL_HOUR_UNIT, 2);
	$WARRIOR_IDEAL_HOUR_MASS = $WARRIOR_IDEAL_HOUR_UNIT * $WARRIOR_PACKAGE_UNIT_MASS[$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS];
	$WARRIOR_IDEAL_HOUR_MASS = varcharTOnumeric2($WARRIOR_IDEAL_HOUR_MASS);
}

/* ASSESS CONDITION OF DOWNTIME */
function model_WARRIOR_assess_condition_of_downtime ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_assess_condition_of_downtime(); */

	/* GLOBALIZE VARIABLES */
	global $WARRIOR_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION,$WARRIOR_DOWNTIME_ACTIVE_CORRECTIVE_ACTION,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME;

	/* -- BUGFIX 20121211
	      -- INSTANCE WHERE SCHEDULED DOWN or DOWN WITH CORRECTIVE ACTION ENTERED IS PRECEDED CHRONOLOGICALLY BY
		 OTHER INSTANCE WHERE DOWN WITHOUT CORRECTIVE ACTION IS FOUND, REUSE PREVIOUS CORRECTIVE
		 ACTION TO ENSURE PROPER REPORTING
	      -- WE WANT TO "BACKFILL" CORRECTIVE ACTIONS, BUT ONLY IN INSTANCES WHERE THE MOST RECENT IS REPLACING
		 A LACK OF ANY.  IF MOST RECENT IS REPLACING SOME OTHER CORRECTIVE ACTION, THEN DO NOT BACKFILL. */
	if ( ($WARRIOR_RESULT_CURRENT_STATE <= 2) && ($WARRIOR_SCHEDULED_DOWNTIME_ACTIVE == 1) && ($WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION != 0) && ($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION == 0) ) {
		$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION;
	} else {
		/* pass */
	}

	/* EXECUTE */
	if ($WARRIOR_RESULT_CURRENT_STATE <= 2) {
		if ( ($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION >= 2) && ($WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION <= 3) ) {
			$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME = 1;
			$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME = 0;
		} else {
			$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME = 1;
			$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME = 0;
		}
	} else {
		/* pass */
	}
}

/* UPDATE DOWNTIME CHECKSTOPS */
function model_WARRIOR_update_downtime_checkstops ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_update_downtime_checkstops(); */

	/* GLOBALIZE VARIABLES */
	global $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME,$WARRIOR_DOWNTIME_ACTIVE,$WARRIOR_DOWNTIME_ACTIVE_START,$WARRIOR_DOWNTIME_ACTIVE_END,$WARRIOR_RESULT_CURRENT_DATESTAMP_START,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME,$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME,$WARRIOR_PROCESS_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END,$WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE;

	/* EXECUTE */
	if ($WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME == 1) {
		if ($WARRIOR_DOWNTIME_ACTIVE == 1) {
			$WARRIOR_DOWNTIME_ACTIVE_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		} else {
			$WARRIOR_DOWNTIME_ACTIVE_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
			$WARRIOR_DOWNTIME_ACTIVE_END = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		}
		if ($WARRIOR_SCHEDULED_DOWNTIME_ACTIVE == 1) {
			$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		} else {
			/* pass */
		}
		$WARRIOR_DOWNTIME_ACTIVE = 1;
		/* BUGFIX 20110705 */
		/* $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE = 0; */
		$WARRIOR_CONDITION_ACTIVE_THIS_DATA_DOWNTIME = 0;
	} else {
		if ($WARRIOR_DOWNTIME_ACTIVE == 1) {
			$WARRIOR_PROCESS_DOWNTIME_ACTIVE = 1;
		} else {
			$WARRIOR_PROCESS_DOWNTIME_ACTIVE = 0;
		}
		$WARRIOR_DOWNTIME_ACTIVE = 0;
	}
	if ($WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME == 1) {
		if ($WARRIOR_SCHEDULED_DOWNTIME_ACTIVE == 1) {
			$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		} else {
			$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION = $WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION;
			$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
			$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		}
		if ($WARRIOR_DOWNTIME_ACTIVE == 1) {
			$WARRIOR_DOWNTIME_ACTIVE_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		} else {
			/* pass */
		}
		$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE = 1;
		/* BUGFIX 20110705 */
		/* $WARRIOR_DOWNTIME_ACTIVE = 0; */
		$WARRIOR_CONDITION_ACTIVE_THIS_DATA_SCHEDULED_DOWNTIME = 0;
	} else {
		if ($WARRIOR_SCHEDULED_DOWNTIME_ACTIVE == 1) {
			$WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE = 1;
		} else {
			$WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE = 0;
		}
		$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE = 0;
	}
}

/* UPDATE DOWNTIME TOTALS */
function model_WARRIOR_update_downtime_totals ($USELONGFORM="NO")
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_update_downtime_totals($USELONGFORM="NO"); */

	/* GLOBALIZE VARIABLES */
	/* 	-- ALL */
	global $WARRIOR_RESULT_CURRENT_SCH_ALARM_FLAG_BGCOLOR,$WARRIOR_PROCESS_DOWNTIME_ACTIVE,$apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME,$apache_function_ENDTIME,$apache_function_STARTTIME,$mysql_WORKING_RUN_MACHINE,$WARRIOR_DOWNTIME_ACTIVE,$WARRIOR_DOWNTIME_ACTIVE_CORRECTIVE_ACTION,$WARRIOR_DOWNTIME_ACTIVE_END,$WARRIOR_DOWNTIME_ACTIVE_END,$WARRIOR_DOWNTIME_ACTIVE_IDENTITY,$WARRIOR_DOWNTIME_ACTIVE_START,$WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_RESULT_CURRENT_ALARM_FLAG_BGCOLOR,$WARRIOR_RESULT_CURRENT_JOB_NUMBER,$WARRIOR_RESULT_CURRENT_OPERATOR,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER,$WARRIOR_RUN_ALARM_ALARM,$WARRIOR_RUN_ALARM_CORRECTIVE_ACTION,$WARRIOR_RUN_ALARM_COUNT,$WARRIOR_RUN_ALARM_DURATION,$WARRIOR_RUN_ALARM_END,$WARRIOR_RUN_ALARM_FLAG_COLOR,$WARRIOR_RUN_ALARM_JOB_DESCRIPTION,$WARRIOR_RUN_ALARM_OPERATOR,$WARRIOR_RUN_ALARM_PACKAGE_CLASS,$WARRIOR_RUN_ALARM_SCHEDULE_NUMBER,$WARRIOR_RUN_ALARM_START,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_IDENTITY,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START,$WARRIOR_TOTAL_DOWNTIME_UNIXTIME,$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME,$WARRIOR_WORKING_WITH_ALARM;

	/* EXECUTE */
	if ($WARRIOR_PROCESS_DOWNTIME_ACTIVE == 1) {
		/* UPDATE DOWNTIME TOTALS */
		if ($USELONGFORM == 'NO') {
			$apache_function_STARTTIME = $WARRIOR_DOWNTIME_ACTIVE_START;
			$apache_function_ENDTIME = $WARRIOR_DOWNTIME_ACTIVE_END;
			list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
			$WARRIOR_TOTAL_DOWNTIME_UNIXTIME = $WARRIOR_TOTAL_DOWNTIME_UNIXTIME + $apache_function_DURATION_UNIXTIME;
		} else {
			$WARRIOR_RUN_ALARM_COUNT[$mysql_WORKING_RUN_MACHINE] =  $WARRIOR_RUN_ALARM_COUNT[$mysql_WORKING_RUN_MACHINE] + 1;
			$WARRIOR_WORKING_WITH_ALARM = $WARRIOR_RUN_ALARM_COUNT[$mysql_WORKING_RUN_MACHINE];
			$WARRIOR_RUN_ALARM_FLAG_COLOR[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_ALARM_FLAG_BGCOLOR;
			$apache_function_STARTTIME = $WARRIOR_DOWNTIME_ACTIVE_START;
			$apache_function_ENDTIME = $WARRIOR_DOWNTIME_ACTIVE_END;
			list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
			$WARRIOR_TOTAL_DOWNTIME_UNIXTIME = $WARRIOR_TOTAL_DOWNTIME_UNIXTIME + $apache_function_DURATION_UNIXTIME;
			$WARRIOR_RUN_ALARM_START[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $apache_function_STARTTIME;
			$WARRIOR_RUN_ALARM_END[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $apache_function_ENDTIME;
			$WARRIOR_RUN_ALARM_DURATION[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = varcharTOnumeric2(($apache_function_DURATION_UNIXTIME / 60), 2);
			$WARRIOR_RUN_ALARM_ALARM[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_DOWNTIME_ACTIVE_IDENTITY;
			$WARRIOR_RUN_ALARM_CORRECTIVE_ACTION[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_DOWNTIME_ACTIVE_CORRECTIVE_ACTION;
			$WARRIOR_RUN_ALARM_SCHEDULE_NUMBER[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER;
			$WARRIOR_RUN_ALARM_PACKAGE_CLASS[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_PACKAGE_CLASS;
			$WARRIOR_RUN_ALARM_JOB_DESCRIPTION[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_JOB_NUMBER;
			$WARRIOR_RUN_ALARM_OPERATOR[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_OPERATOR;
		}
		/* UNLATCH */
		$WARRIOR_DOWNTIME_ACTIVE = 0;
	} else {
		/* pass */
	}
	if ($WARRIOR_PROCESS_SCHEDULED_DOWNTIME_ACTIVE == 1) {
		/* UPDATE SCHEDULED_DOWNTIME TOTALS */
		if ($USELONGFORM == 'NO') {
			$apache_function_STARTTIME = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START;
			$apache_function_ENDTIME = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END;
			list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
			$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME = $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME + $apache_function_DURATION_UNIXTIME;
		} else {
			$WARRIOR_RUN_ALARM_COUNT[$mysql_WORKING_RUN_MACHINE] =  $WARRIOR_RUN_ALARM_COUNT[$mysql_WORKING_RUN_MACHINE] + 1;
			$WARRIOR_WORKING_WITH_ALARM = $WARRIOR_RUN_ALARM_COUNT[$mysql_WORKING_RUN_MACHINE];
			$WARRIOR_RUN_ALARM_FLAG_COLOR[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_SCH_ALARM_FLAG_BGCOLOR;
			$apache_function_STARTTIME = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START;
			$apache_function_ENDTIME = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END;
			list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
			$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME = $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME + $apache_function_DURATION_UNIXTIME;
			$WARRIOR_RUN_ALARM_START[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $apache_function_STARTTIME;
			$WARRIOR_RUN_ALARM_END[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $apache_function_ENDTIME;
			$WARRIOR_RUN_ALARM_DURATION[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = varcharTOnumeric2(($apache_function_DURATION_UNIXTIME / 60), 2);
			$WARRIOR_RUN_ALARM_ALARM[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_IDENTITY;
			$WARRIOR_RUN_ALARM_CORRECTIVE_ACTION[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_CORRECTIVE_ACTION;
			$WARRIOR_RUN_ALARM_SCHEDULE_NUMBER[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER;
			$WARRIOR_RUN_ALARM_PACKAGE_CLASS[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_PACKAGE_CLASS;
			$WARRIOR_RUN_ALARM_JOB_DESCRIPTION[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_JOB_NUMBER;
			$WARRIOR_RUN_ALARM_OPERATOR[$WARRIOR_WORKING_WITH_ALARM][$mysql_WORKING_RUN_MACHINE] = $WARRIOR_RESULT_CURRENT_OPERATOR;
		}
		/* UNLATCH */
		$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE = 0;
	} else {
		/* pass */
	}
}

/* SCRUTINIZE DOWNTIME HISTORY */
function model_WARRIOR_scrutinize_history ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_scrutinize_history(); */

	/* GLOBALIZE VARIABLES */
	global $WARRIOR_RESULT_TEST_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER,$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER,$WARRIOR_RESULT_CURRENT_JOB_NUMBER,$WARRIOR_CHECKSTOP_JOB_NUMBER,$WARRIOR_RESULT_CURRENT_CYCLES_START,$WARRIOR_CHECKSTOP_CYCLES,$WARRIOR_EXAMINE_RECENT_HISTORY,$WARRIOR_RESULT_CURRENT_CYCLES_START,$WARRIOR_RESULT_CURRENT_DATESTAMP_START,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_RESULT_CURRENT_ALARM,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_CHECKSTOP_JOB_NUMBER,$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER,$WARRIOR_CHECKSTOP_CORRECTIVE_ACTION,$WARRIOR_CHECKSTOP_ALARM,$WARRIOR_CHECKSTOP_STATE,$WARRIOR_CHECKSTOP_DATESTAMP_START,$WARRIOR_CHECKSTOP_CYCLES;

	/* EXECUTE */
	if ( ($WARRIOR_RESULT_TEST_PACKAGE_CLASS != $WARRIOR_RESULT_CURRENT_PACKAGE_CLASS) || ($WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER != $WARRIOR_CHECKSTOP_SCHEDULE_NUMBER) || ($WARRIOR_RESULT_CURRENT_JOB_NUMBER != $WARRIOR_CHECKSTOP_JOB_NUMBER) || ($WARRIOR_RESULT_CURRENT_CYCLES_START > $WARRIOR_CHECKSTOP_CYCLES) ) {
		/* BREAK THE CYCLE - WE SEE A CHANGE IN JOB OR SCHEDULE, SO THAT'S THE BEGINNING OF THE RUN */
		$WARRIOR_EXAMINE_RECENT_HISTORY = 0;
	} else {
		/* UPDATE CHECKSTOPS */
		$WARRIOR_CHECKSTOP_JOB_NUMBER = $WARRIOR_RESULT_CURRENT_JOB_NUMBER;
		$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER = $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER;
		$WARRIOR_CHECKSTOP_CORRECTIVE_ACTION = $WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION;
		$WARRIOR_CHECKSTOP_ALARM = $WARRIOR_RESULT_CURRENT_ALARM;
		$WARRIOR_CHECKSTOP_STATE = $WARRIOR_RESULT_CURRENT_STATE;
		$WARRIOR_CHECKSTOP_DATESTAMP_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		$WARRIOR_CHECKSTOP_CYCLES = $WARRIOR_RESULT_CURRENT_CYCLES_START;
	}
}

/* SCRUTINIZE DOWNTIME HISTORY - REVISION 2 */
function model_WARRIOR_scrutinize_history_REV2 ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_scrutinize_history_REV2(); */

	/* GLOBALIZE VARIABLES */
	global $WARRIOR_RESULT_TEST_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_PACKAGE_CLASS,$WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER,$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER,$WARRIOR_RESULT_CURRENT_JOB_NUMBER,$WARRIOR_CHECKSTOP_JOB_NUMBER,$WARRIOR_RESULT_CURRENT_CYCLES_START,$WARRIOR_CHECKSTOP_CYCLES,$WARRIOR_EXAMINE_RECENT_HISTORY,$WARRIOR_RESULT_CURRENT_CYCLES_START,$WARRIOR_RESULT_CURRENT_DATESTAMP_START,$WARRIOR_RESULT_CURRENT_STATE,$WARRIOR_RESULT_CURRENT_ALARM,$WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION,$WARRIOR_CHECKSTOP_JOB_NUMBER,$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER,$WARRIOR_CHECKSTOP_CORRECTIVE_ACTION,$WARRIOR_CHECKSTOP_ALARM,$WARRIOR_CHECKSTOP_STATE,$WARRIOR_CHECKSTOP_DATESTAMP_START,$WARRIOR_CHECKSTOP_CYCLES;

	/* EXECUTE */
	if ( ($WARRIOR_RESULT_TEST_PACKAGE_CLASS != $WARRIOR_RESULT_CURRENT_PACKAGE_CLASS) || ($WARRIOR_RESULT_CURRENT_CYCLES_START > $WARRIOR_CHECKSTOP_CYCLES) ) {
		/* BREAK THE CYCLE - WE SEE A CHANGE IN JOB OR SCHEDULE, SO THAT'S THE BEGINNING OF THE RUN */
		$WARRIOR_EXAMINE_RECENT_HISTORY = 0;
	} else {
		/* UPDATE CHECKSTOPS */
		if ($WARRIOR_RESULT_CURRENT_JOB_NUMBER != 0) {
			/* THIS MAY OR MAY NOT BE NECESSARY */
			$WARRIOR_CHECKSTOP_JOB_NUMBER = $WARRIOR_RESULT_CURRENT_JOB_NUMBER;
		} else {
			/* pass */
		}
		$WARRIOR_CHECKSTOP_SCHEDULE_NUMBER = $WARRIOR_RESULT_CURRENT_SCHEDULE_NUMBER;
		$WARRIOR_CHECKSTOP_CORRECTIVE_ACTION = $WARRIOR_RESULT_CURRENT_CORRECTIVE_ACTION;
		$WARRIOR_CHECKSTOP_ALARM = $WARRIOR_RESULT_CURRENT_ALARM;
		$WARRIOR_CHECKSTOP_STATE = $WARRIOR_RESULT_CURRENT_STATE;
		$WARRIOR_CHECKSTOP_DATESTAMP_START = $WARRIOR_RESULT_CURRENT_DATESTAMP_START;
		$WARRIOR_CHECKSTOP_CYCLES = $WARRIOR_RESULT_CURRENT_CYCLES_START;
	}
}

/* STRAGGLER DOWNTIME ACTIVE CLEANUP */
function model_WARRIOR_straggler_downtime_active_cleanup ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_straggler_downtime_active_cleanup(); */

	/* GLOBALIZE VARIABLES */
	global $WARRIOR_DOWNTIME_ACTIVE,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE,$WARRIOR_DOWNTIME_ACTIVE_START,$WARRIOR_DOWNTIME_ACTIVE_END,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START,$WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END,$WARRIOR_TOTAL_DOWNTIME_UNIXTIME,$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME;

	/* EXECUTE */
	if ($WARRIOR_DOWNTIME_ACTIVE == 1) {
		/* UPDATE DOWNTIME TOTALS */
		$apache_function_STARTTIME = $WARRIOR_DOWNTIME_ACTIVE_START;
		$apache_function_ENDTIME = $WARRIOR_DOWNTIME_ACTIVE_END;
		list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
		$WARRIOR_TOTAL_DOWNTIME_UNIXTIME = $WARRIOR_TOTAL_DOWNTIME_UNIXTIME + $apache_function_DURATION_UNIXTIME;
	} else {
		/* pass */
	}
	if ($WARRIOR_SCHEDULED_DOWNTIME_ACTIVE == 1) {
		/* UPDATE SCHEDULED_DOWNTIME TOTALS */
		$apache_function_STARTTIME = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_START;
		$apache_function_ENDTIME = $WARRIOR_SCHEDULED_DOWNTIME_ACTIVE_END;
		list($apache_function_DURATION_FINAL,$apache_function_DURATION_UNIXTIME) = timeDuration($apache_function_STARTTIME,$apache_function_ENDTIME);
		$WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME = $WARRIOR_TOTAL_SCHEDULED_DOWNTIME_UNIXTIME + $apache_function_DURATION_UNIXTIME;
	} else {
		/* pass */
	}
}

/* HMI 0 - DETERMINE ACTION MODE */
function model_WARRIOR_hmi_0_determine_action_mode ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_hmi_0_determine_action_mode(); */

	/* GLOBALIZE VARIABLES */
	/*	-- MODEL SPECIFIC */
	global $WARRIOR_NAME;

	/* 	-- APACHE */
	global $seer_HMIACTION,$seer_HMIACTION_FAULT,$seer_MACHINE_TO_DISPLAY,$seer_MACHINE_TO_DISPLAY_FRIENDLYNAME,$apache_PAGETYPE;

	/* EXECUTE */
	if ( $_POST[seer_HMIACTION] != '' ) {
		$seer_HMIACTION = $_POST['seer_HMIACTION'];
		$seer_HMIACTION_FAULT = 0;

		if ($seer_HMIACTION == 'DISPLAY_MACHINE_PAGE') {
			if ( $_POST[seer_MACHINE_TO_DISPLAY] != '') {
				$seer_MACHINE_TO_DISPLAY = $_POST['seer_MACHINE_TO_DISPLAY'];
				$seer_MACHINE_TO_DISPLAY_FRIENDLYNAME = $WARRIOR_NAME[$seer_MACHINE_TO_DISPLAY];
			} else {
				if ( $_GET[seer_MACHINE_TO_DISPLAY] != '') {
					$seer_MACHINE_TO_DISPLAY = $_GET['seer_MACHINE_TO_DISPLAY'];
					$seer_MACHINE_TO_DISPLAY_FRIENDLYNAME = $WARRIOR_NAME[$seer_MACHINE_TO_DISPLAY];
				} else {
					$seer_HMIACTION = "DISPLAY_START_PAGE";
					$apache_PAGETYPE = "STATIC";
				}
			}
		} else {
			/* pass */
		}

	} else {
		if ( $_GET[seer_HMIACTION] != '' ) {
			$seer_HMIACTION = $_GET['seer_HMIACTION'];
			$seer_HMIACTION_FAULT = 0;

			if ($seer_HMIACTION == 'DISPLAY_MACHINE_PAGE') {
				if ( $_GET[seer_MACHINE_TO_DISPLAY] != '') {
					$seer_MACHINE_TO_DISPLAY = $_GET['seer_MACHINE_TO_DISPLAY'];
					$seer_MACHINE_TO_DISPLAY_FRIENDLYNAME = $WARRIOR_NAME[$seer_MACHINE_TO_DISPLAY];
				} else {
					if ( $_POST[seer_MACHINE_TO_DISPLAY] != '') {
						$seer_MACHINE_TO_DISPLAY = $_POST['seer_MACHINE_TO_DISPLAY'];
						$seer_MACHINE_TO_DISPLAY_FRIENDLYNAME = $WARRIOR_NAME[$seer_MACHINE_TO_DISPLAY];
					} else {
						$seer_HMIACTION = "DISPLAY_START_PAGE";
						$apache_PAGETYPE = "STATIC";
					}
				}
			} else {
				/* pass */
			}

		} else {
			$seer_HMIACTION = "DISPLAY_START_PAGE";
			$apache_PAGETYPE = "STATIC";
			/*	-- do not auto refresh this page */
		}
	}
}

/* HMI and REPORT DATE START and END USER RE-RUN THE JOB FORM */
/* -- prompt user for input and build the form for submission */
/* -- TYPE w1 */
function core_user_date_time_range_rerun_type_w1 ($request_detail_level="NO")
{
	/* CALL THIS FUNCTION WITH... */
	/* $my_recordentry = core_user_date_time_range_rerun_type_w1($request_detail_level="NO"); */

	/* GLOBALIZE VARIABLES */
	/*	-- SEER */
	global $seer_REFERRINGPAGE;

	/*	-- MYSQL */
	global $mysql_ENTRY_START_YEAR,$mysql_ENTRY_START_MONTH,$mysql_ENTRY_START_DAY,$mysql_ENTRY_END_MONTH,$mysql_ENTRY_END_DAY;

	/*	-- APACHE */
	global $apache_REPORT_RECORDENTRY;

	/*	-- MODEL SPECIFIC */
	global $WARRIOR_FORMFILL_SHIFT_NAME;

	/*	-- LANGUAGE */
	global $multilang_STATIC_RERUN_REPORT,$multilang_WARRIOR_112,$multilang_WARRIOR_108,$multilang_WARRIOR_112,$multilang_WARRIOR_109,$multilang_WARRIOR_112,$multilang_WARRIOR_110,$multilang_WARRIOR_112,$multilang_WARRIOR_111,$multilang_STATIC_DISPLAY_REPORT_TICKET,$multilang_WARRIOR_74,$multilang_WARRIOR_75,$multilang_WARRIOR_90,$multilang_WARRIOR_27,$multilang_WARRIOR_77,$multilang_WARRIOR_76,$multilang_WARRIOR_78,$multilang_WARRIOR_79,$multilang_STATIC_HOUR;



	/* EXECUTE */
	list($apache_THISYEAR,$apache_LASTYEAR,$apache_THISMONTH,$apache_THISDAYOFMONTH,$apache_THISHOUR,$apache_THISMINUTE,$apache_THISSECOND,$apache_FORMFILL_MANUAL_ENTRY_YEAR,$apache_FORMFILL_MANUAL_ENTRY_MONTH,$apache_FORMFILL_MANUAL_ENTRY_DAY,$apache_FORMFILL_MANUAL_ENTRY_HOUR,$apache_FORMFILL_MANUAL_ENTRY_MINUTE) = discretedatestampZEROBASE($mysql_mod_openopc_RETENTION_YEARS);
	
	$post_form_to_display = "
									<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
									<!-- HMI and REPORT DATE START and END RE-RUN THE JOB INPUT FIELDS -->
									<!-- TYPE w1 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
									<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->

									<FORM ACTION='".$seer_REFERRINGPAGE."' METHOD='post'>
										<TABLE CLASS='SMALL' WIDTH='750' ALIGN='CENTER' CELLPADDING=0 CELLSPACING=0>
											<TR>
												<TD WIDTH='750'>
													<BR>
												</TD>
											</TR>
											<TR>
												<TD CLASS='hmicellborder1'>
													<TABLE CLASS='SMALL' WIDTH='750' ALIGN='CENTER' CELLPADDING=0 CELLSPACING=0>
														<TR>
															<TD WIDTH='200'>
															</TD>
															<TD WIDTH='50'>
															</TD>
															<TD WIDTH='500'>
															</TD>
														</TR>
														<TR>
															<TD COLSPAN='3'>
																<BR>
															</TD>
														</TR>
														<TR>
															<TD ALIGN='RIGHT' VALIGN='TOP'>
																<B><I>".$multilang_STATIC_RERUN_REPORT."... </I></B><BR>
															</TD>
															<TD>
																<BR>
															</TD>
															<TD ALIGN='LEFT' VALIGN='TOP'>
																<TABLE CLASS='SMALL' WIDTH='500' ALIGN='CENTER' CELLPADDING=0 CELLSPACING=0>
																	<TR>
																		<TD WIDTH='250'>
																		</TD>
																		<TD WIDTH='250'>
																		</TD>
																	</TR>
																	<TR>
																		<TD ALIGN='LEFT'>
																			<I>".$multilang_WARRIOR_75."...</I><BR>
																			<SELECT NAME='mysql_ENTRY_SHIFT'><OPTION VALUE=''>".$multilang_WARRIOR_27."<OPTION VALUE='88888'>".$multilang_WARRIOR_77.$WARRIOR_FORMFILL_SHIFT_NAME."<OPTION VALUE='99999'>".$multilang_WARRIOR_76."</SELECT>
																		</TD>
																		<TD>
																		</TD>
																	</TR>
																	<TR>
																		<TD COLSPAN='2'>
																			<BR>
																		</TD>
																	</TR>
																	<TR>
																		<TD ALIGN='LEFT'>
																			<I>".$multilang_WARRIOR_78."...</I><BR>
																			<SELECT NAME='mysql_ENTRY_SHIFT_CUSTOM_START_HOUR'><OPTION VALUE=''>".$multilang_STATIC_HOUR.$apache_FORMFILL_MANUAL_ENTRY_HOUR."</SELECT>
																		</TD>
																		<TD ALIGN='LEFT'>
																			<I>".$multilang_WARRIOR_79."...</I><BR>
																			<SELECT NAME='mysql_ENTRY_SHIFT_CUSTOM_END_HOUR'><OPTION VALUE=''>".$multilang_STATIC_HOUR.$apache_FORMFILL_MANUAL_ENTRY_HOUR."</SELECT>
																		</TD>
																	</TR>
																</TABLE>
															</TD>
														</TR>
														<TR>
															<TD COLSPAN='3'>
																<BR>
															</TD>
														</TR>
														<TR>
															<TD COLSPAN='2'>
															</TD>
															";
	if ($request_detail_level != 'NO') {
			$post_form_to_display = $post_form_to_display."
															<TD ALIGN='LEFT'>
																<I>".$multilang_WARRIOR_112."...</I><BR>
																<SELECT NAME='mysql_DETAIL_LEVEL'><OPTION VALUE='SUMMARY'>".$multilang_WARRIOR_108."<OPTION VALUE='MEDIUM'>".$multilang_WARRIOR_109."<OPTION VALUE='HIGH'>".$multilang_WARRIOR_110."<OPTION VALUE='EXTREME'>".$multilang_WARRIOR_111."</SELECT>
															</TD>
															";
	} else {
			$post_form_to_display = $post_form_to_display."
															<TD>
															</TD>
															";
	}
	$post_form_to_display = $post_form_to_display."
														</TR>
														<TR>
															<TD COLSPAN='3'>
																<INPUT TYPE='hidden' name='seer_HMIACTION' value='BUILDTICKET'>
																<INPUT TYPE='hidden' name='mysql_ENTRY_START_YEAR' value='$mysql_ENTRY_START_YEAR'>
																<INPUT TYPE='hidden' name='mysql_ENTRY_START_MONTH' value='$mysql_ENTRY_START_MONTH'>
																<INPUT TYPE='hidden' name='mysql_ENTRY_START_DAY' value='$mysql_ENTRY_START_DAY'>
																<INPUT TYPE='hidden' name='mysql_ENTRY_END_MONTH' value='$mysql_ENTRY_END_MONTH'>
																<INPUT TYPE='hidden' name='mysql_ENTRY_END_DAY' value='$mysql_ENTRY_END_DAY'>
																
															</TD>
														</TR>
														<TR>
															<TD COLSPAN='3'>
																<BR>
															</TD>
														</TR>
														<TR>
															<TD>
																<BR>
															</TD>
															<TD>
																<BR>
															</TD>
															<TD ALIGN='LEFT'>
																<INPUT TYPE='image' name='enter' src='./img/form_submit_0.png'>
															</TD>
														</TR>
														<TR>
															<TD COLSPAN='3'>
																<BR>
															</TD>
														</TR>
													</TABLE>
												</TD>
											</TR>
										</TABLE>
									</FORM>

									<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
									";


	/* RETURN VARIABLES */
	return $post_form_to_display;
}

/* HMI and REPORT DATE START and END USER INPUT FIELDS (ASK FOR) */
/* -- prompt user for input and build the form for submission */
/* -- TYPE w1 */
function model_WARRIOR_user_date_time_range_prompt_type_w1 ($request_detail_level="NO")
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_user_date_time_range_prompt_type_w1($request_detail_level="NO"); */

	/* GLOBALIZE VARIABLES */
	/*	--  MODOPENOPC */
	global $mysql_mod_openopc_RETENTION_YEARS;

	/*	-- SEER */
	global $seer_REFERRINGPAGE;

	/*	-- APACHE */
	global $apache_REPORT_RECORDENTRY;

	/*	-- MODEL SPECIFIC */
	global $WARRIOR_FORMFILL_SHIFT_NAME;

	/*	-- LANGUAGE */
	global $multilang_WARRIOR_112,$multilang_WARRIOR_108,$multilang_WARRIOR_112,$multilang_WARRIOR_109,$multilang_WARRIOR_112,$multilang_WARRIOR_110,$multilang_WARRIOR_112,$multilang_WARRIOR_111,$multilang_STATIC_DISPLAY_REPORT_TICKET,$multilang_STATIC_DATESTAMP,$multilang_STATIC_START_OF_LOG,$multilang_STATIC_SNAPSHOT_LENGTH,$multilang_STATIC_END_OF_LOG,$multilang_STATIC_MONTHS,$multilang_STATIC_DAYS,$multilang_STATIC_YEAR,$multilang_STATIC_MONTH,$multilang_STATIC_DAY,$multilang_STATIC_NOTE,$multilang_WARRIOR_74,$multilang_WARRIOR_75,$multilang_WARRIOR_90,$multilang_WARRIOR_27,$multilang_WARRIOR_77,$multilang_WARRIOR_76,$multilang_WARRIOR_78,$multilang_WARRIOR_79,$multilang_STATIC_HOUR;

	/* CALL FUNCTIONS FOR THIS HMI */
	/* -- DISCRETE DATESTAMP TAGS */
	list($apache_THISYEAR,$apache_LASTYEAR,$apache_THISMONTH,$apache_THISDAYOFMONTH,$apache_THISHOUR,$apache_THISMINUTE,$apache_THISSECOND,$apache_FORMFILL_MANUAL_ENTRY_YEAR,$apache_FORMFILL_MANUAL_ENTRY_MONTH,$apache_FORMFILL_MANUAL_ENTRY_DAY,$apache_FORMFILL_MANUAL_ENTRY_HOUR,$apache_FORMFILL_MANUAL_ENTRY_MINUTE) = discretedatestampZEROBASE($mysql_mod_openopc_RETENTION_YEARS);
	$apache_FORMFILL_LENGTH_MONTHS = zerothehero(0,6,1);
	$apache_FORMFILL_LENGTH_DAYS = zerothehero(0,31,1);
	
	$apache_REPORT_RECORDENTRY = "
						<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
						<!-- HMI and REPORT DATE START and END USER INPUT FIELDS (ASK FOR) -->
						<!-- TYPE w1 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
						<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->

						<FORM ACTION='".$seer_REFERRINGPAGE."' METHOD='POST'>
							<TABLE CLASS='STANDARD' ALIGN='CENTER' WIDTH='600'>
								<TR>
									<TD WIDTH='100'>
									</TD>
									<TD WIDTH='200'>
									</TD>
									<TD WIDTH='200'>
									</TD>
									<TD WIDTH='100'>
									</TD>
								</TR>
								<TR>
									<TD COLSPAN='4'>
										<BR>
									</TD>
								</TR>
								<TR>
									<TD COLSPAN='4'>
										<P CLASS='INFOREPORT'>
											<B><U>".$multilang_STATIC_NOTE." 1:</U></B> ".$multilang_WARRIOR_74."<BR>
											<BR>
											<B><U>".$multilang_STATIC_NOTE." 2:</U></B> ".$multilang_WARRIOR_90."<BR>
										</P>
									</TD>
								</TR>
								<TR>
									<TD>
										<B><I>".$multilang_WARRIOR_75."</I></B>
									</TD>
									<TD>
										<SELECT NAME='mysql_ENTRY_SHIFT'><OPTION VALUE=''>".$multilang_WARRIOR_27."<OPTION VALUE='88888'>".$multilang_WARRIOR_77.$WARRIOR_FORMFILL_SHIFT_NAME."<OPTION VALUE='99999'>".$multilang_WARRIOR_76."</SELECT>
									</TD>
									<TD>
										<B><I>".$multilang_WARRIOR_78."</I></B>
									</TD>
									<TD>
										<SELECT NAME='mysql_ENTRY_SHIFT_CUSTOM_START_HOUR'><OPTION VALUE=''>".$multilang_STATIC_HOUR.$apache_FORMFILL_MANUAL_ENTRY_HOUR."</SELECT>
									</TD>
								</TR>
								<TR>
									<TD COLSPAN='2'>
										<BR>
									</TD>
									<TD>
										<B><I>".$multilang_WARRIOR_79."</I></B>
									</TD>
									<TD>
										<SELECT NAME='mysql_ENTRY_SHIFT_CUSTOM_END_HOUR'><OPTION VALUE=''>".$multilang_STATIC_HOUR.$apache_FORMFILL_MANUAL_ENTRY_HOUR."</SELECT>
									</TD>
								<TR>
									<TD COLSPAN='4'>
										<BR>
										<BR>
									</TD>
								</TR>
								";
		if ($request_detail_level == 'YES') {
			$apache_REPORT_RECORDENTRY = $apache_REPORT_RECORDENTRY."
								<TR>
									<TD>
										<B><I>".$multilang_WARRIOR_112."</I></B>
									</TD>
									<TD COLSPAN='3'>
										<SELECT NAME='mysql_DETAIL_LEVEL'><OPTION VALUE='SUMMARY'>".$multilang_WARRIOR_108."<OPTION VALUE='MEDIUM'>".$multilang_WARRIOR_109."<OPTION VALUE='HIGH'>".$multilang_WARRIOR_110."<OPTION VALUE='EXTREME'>".$multilang_WARRIOR_111."</SELECT>
									</TD>
								<TR>
									<TD COLSPAN='4'>
										<BR>
										<BR>
									</TD>
								</TR>
								";
		} else {
			/* pass */
		}
		$apache_REPORT_RECORDENTRY = $apache_REPORT_RECORDENTRY."
								<TR>
									<TD>
										<BR>
									</TD>
									<TD COLSPAN='3'>
										<TABLE CLASS='STANDARD' ALIGN='LEFT' WIDTH='500'>
											<TR>
												<TD WIDTH='100'>
													<B>".$multilang_STATIC_YEAR."</B>
												</TD>
												<TD WIDTH='100'>
													<B>".$multilang_STATIC_MONTH."</B>
												</TD>
												<TD WIDTH='100'>
													<B>".$multilang_STATIC_DAY."</B>
												</TD>
												<TD WIDTH='100'>
													<BR>
												</TD>
												<TD WIDTH='100'>
													<BR>
												</TD>
											</TR>
										</TABLE>
									</TD>
								</TR>
								<TR>
									<TD>
										<B><I>".$multilang_STATIC_DATESTAMP."<BR>
										[".$multilang_STATIC_START_OF_LOG."]</I></B>
									</TD>
									<TD COLSPAN='3'>
										<TABLE CLASS='STANDARD' ALIGN='LEFT' WIDTH='500'>
											<TR>
												<TD WIDTH='100'>
													<SELECT NAME='mysql_ENTRY_START_YEAR'><OPTION VALUE=''>".$multilang_STATIC_YEAR.$apache_FORMFILL_MANUAL_ENTRY_YEAR."</SELECT>
												</TD>
												<TD WIDTH='100'>
													<SELECT NAME='mysql_ENTRY_START_MONTH'><OPTION VALUE=''>".$multilang_STATIC_MONTH.$apache_FORMFILL_MANUAL_ENTRY_MONTH."</SELECT>
												</TD>
												<TD WIDTH='100'>
													<SELECT NAME='mysql_ENTRY_START_DAY'><OPTION VALUE=''>".$multilang_STATIC_DAY.$apache_FORMFILL_MANUAL_ENTRY_DAY."</SELECT>
												</TD>
												<TD WIDTH='100'>
													<BR>
												</TD>
												<TD WIDTH='100'>
													<BR>
												</TD>
											</TR>
										</TABLE>
									</TD>
								</TR>
								<TR>
									<TD COLSPAN='4'>
										<BR>
										<BR>
									</TD>
								</TR>
								<TR>
									<TD>
										<B><I>".$multilang_STATIC_SNAPSHOT_LENGTH."<BR>
										[".$multilang_STATIC_END_OF_LOG."]</I></B>
									</TD>
									<TD COLSPAN='3'>
										<TABLE CLASS='STANDARD' ALIGN='LEFT' WIDTH='500'>
											<TR>
												<TD WIDTH='100'>
													<BR>
												</TD>
												<TD WIDTH='100'>
													<SELECT NAME='mysql_ENTRY_END_MONTH'><OPTION VALUE=''>".$multilang_STATIC_MONTHS.$apache_FORMFILL_LENGTH_MONTHS."</SELECT>
												</TD>
												<TD WIDTH='100'>
													<SELECT NAME='mysql_ENTRY_END_DAY'><OPTION VALUE=''>".$multilang_STATIC_DAYS.$apache_FORMFILL_LENGTH_DAYS."</SELECT>
												</TD>
												<TD WIDTH='100'>
													<BR>
												</TD>
												<TD WIDTH='100'>
													<BR>
												</TD>
											</TR>
										</TABLE>
									</TD>
								</TR>
								<TR>
									<TD COLSPAN='4'>
										<BR>
										<BR>
									</TD>
								</TR>
								<TR>
									<TD>
										<BR>
									</TD>
									<TD ALIGN='RIGHT'>
										<B><I>".$multilang_STATIC_DISPLAY_REPORT_TICKET."</I></B>
									</TD>
									<TD>
										<INPUT TYPE='hidden' name='seer_HMIACTION' value='BUILDTICKET'>
										<INPUT TYPE='image' name='enter' src='./img/form_submit_0.png'>
									</TD>
									<TD>
										<BR>
									</TD>
								</TR>
							</TABLE>
						</FORM>

						<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->
						";
}

/* REPORT CORRECTIVE ACTION POST MORTUM MODIFICATIONS */
/* -- handle input, update DB and resume normal operation */
/* -- should be called while within a conditional based upon HMIACTION = BUILDTICKET */
function model_WARRIOR_corrective_action_post_mortum ()
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_corrective_action_post_mortum() */

	/* GLOBALIZE VARIABLES */
	/*	-- MYSQL */
	global $WARRIOR_mysql_mod_openopc_TABLENAME_DATA;

	/* EXECUTE */
	if ( $_POST[post_CA_POST_MORTUM_REQUEST_HMIACTION] != '' ) {
		if ( $_POST[post_CA_POST_MORTUM_REQUEST_HMIACTION] == 'YES' ) {
			/* PROCEED WITH USER REQUESTED POST MORTUM UPDATE */
			/* -- CHECK FOR ALL NECESSARY VARIABLES */
			if ( ($_POST[post_CA_POST_MORTUM_MACHINE_NAME] != '') && ($_POST[post_CA_POST_MORTUM_DATESTAMP_START] != '') && ($_POST[post_CA_POST_MORTUM_DATESTAMP_END] != '') && ($_POST[post_CA_POST_MORTUM_VALUE_TO_OVERWRITE] != '') ) {
				/* ALL VARIABLES OK - PROCEED */
				$post_CA_POST_MORTUM_MACHINE_NAME = $_POST['post_CA_POST_MORTUM_MACHINE_NAME'];
				$post_CA_POST_MORTUM_DATESTAMP_START = $_POST['post_CA_POST_MORTUM_DATESTAMP_START'];
				$post_CA_POST_MORTUM_DATESTAMP_END = $_POST['post_CA_POST_MORTUM_DATESTAMP_END'];
				$post_CA_POST_MORTUM_VALUE_TO_OVERWRITE = $_POST['post_CA_POST_MORTUM_VALUE_TO_OVERWRITE'];
				/* BUILD QUERY STRING */
				$mysql_mod_openopc_query = "UPDATE ".$WARRIOR_mysql_mod_openopc_TABLENAME_DATA." SET CORRECTIVE_ACTION='".$post_CA_POST_MORTUM_VALUE_TO_OVERWRITE."' WHERE ((DATESTAMP BETWEEN '".$post_CA_POST_MORTUM_DATESTAMP_START."' AND '".$post_CA_POST_MORTUM_DATESTAMP_END."') AND (MACHINE_NAME LIKE '".$post_CA_POST_MORTUM_MACHINE_NAME."'))";
				/* EXECUTE QUERY */
				core_mysql_mod_openopc_query_shell($mysql_mod_openopc_query);
			} else {
				/* SOME VARIABLE IS MISSING - SILENTLY DISREGARD AND IGNORE REQUEST */
				/* pass */
			}
		} else {
			/* USER HAS NOT REQUESTED A POST MORTUM UPDATE */
			/* pass */
		}
	} else {
		/* USER HAS NOT REQUESTED A POST MORTUM UPDATE */
		/* pass */
	}
}

/* HMI and REPORT DATE START and END USER INPUT ACCEPTANCE */
/* -- handle input, throw a fault if bad, and */
/* -- indicate fault status as present or not */
/* -- TYPE w1 */
function model_WARRIOR_user_date_time_range_input_type_w1 ($request_detail_level="NO")
{
	/* CALL THIS FUNCTION WITH... */
	/* model_WARRIOR_user_date_time_range_input_type_w1($request_detail_level="NO") */

	/* GLOBALIZE VARIABLES */
	/*	-- SEER */
	global $seer_HMIACTION_FAULT,$seer_FAULT_TYPE,$JUMP_FROM_REPORT_0;

	/*	-- MODEL SPECIFIC */
	global $WARRIOR_SHIFT,$WARRIOR_SHIFT_NAME;

	/*	-- LANGUAGE */
	global $multilang_FAULT_35,$multilang_WARRIOR_80,$multilang_WARRIOR_76,$multilang_WARRIOR_77,$multilang_TANKMODEL_75,$multilang_WARRIOR_89,$multilang_FAULT_2,$multilang_FAULT_3,$multilang_FAULT_4,$multilang_FAULT_8,$multilang_FAULT_9;

	/*	-- APACHE */
	global $WARRIOR_TITLE_REPORT_SHIFT_ID;

	/* 	-- MYSQL */
	global $mysql_ENTRY_END_YEAR,$mysql_ENTRY_SHIFT_CUSTOM_START_HOUR,$mysql_ENTRY_SHIFT_CUSTOM_END_HOUR,$mysql_ENTRY_RUN_IDENTIFICATION,$mysql_ENTRY_MACHINENAME,$mysql_query_START_DATESTAMP,$mysql_query_END_DATESTAMP,$mysql_ENTRY_SHIFT,$mysql_ENTRY_START_HOUR,$mysql_ENTRY_START_MINUTE,$mysql_ENTRY_START_HOUR_MINUTE_COMBO,$mysql_ENTRY_END_HOUR,$mysql_ENTRY_END_MINUTE,$mysql_ENTRY_END_HOUR_MINUTE_COMBO,$mysql_ENTRY_START_YEAR,$mysql_ENTRY_START_MONTH,$mysql_ENTRY_START_DAY,$mysql_ENTRY_END_MONTH,$mysql_ENTRY_END_DAY,$mysql_DETAIL_LEVEL;

	/* EXECUTE */
	if ( $_POST[mysql_JUMP_FROM_REPORT_0] != '' ) {
		if ( $_POST[mysql_JUMP_FROM_REPORT_0] == 'YES' ) {
			$JUMP_FROM_REPORT_0 = "YES";
		} else {
			$JUMP_FROM_REPORT_0 = "NO";
		}
	} else {
		$JUMP_FROM_REPORT_0 = "NO";
	}
	if ( $_POST[mysql_ENTRY_SHIFT] != '' ) {
		$mysql_ENTRY_SHIFT = $_POST['mysql_ENTRY_SHIFT'];
		if ($mysql_ENTRY_SHIFT == 99999) {
			if ( $_POST[mysql_ENTRY_SHIFT_CUSTOM_START_HOUR] != '' ) {
				$mysql_ENTRY_SHIFT_CUSTOM_START_HOUR = $_POST['mysql_ENTRY_SHIFT_CUSTOM_START_HOUR'];
				$mysql_ENTRY_START_HOUR = $mysql_ENTRY_SHIFT_CUSTOM_START_HOUR;
				$mysql_ENTRY_START_MINUTE = "00";
				if ($JUMP_FROM_REPORT_0 == 'YES') {
					$mysql_ENTRY_START_HOUR_MINUTE_COMBO = $mysql_ENTRY_START_HOUR;
				} else {
					$mysql_ENTRY_START_HOUR_MINUTE_COMBO = $mysql_ENTRY_START_HOUR.":".$mysql_ENTRY_START_MINUTE;
				}
			} else {
				$mysql_ENTRY_SHIFT_CUSTOM_START_HOUR = "";
				$seer_HMIACTION_FAULT = 1;
				$seer_FAULT_TYPE = $multilang_WARRIOR_80;
			}
			if ( $_POST[mysql_ENTRY_SHIFT_CUSTOM_END_HOUR] != '' ) {
				$mysql_ENTRY_SHIFT_CUSTOM_END_HOUR = $_POST['mysql_ENTRY_SHIFT_CUSTOM_END_HOUR'];
				$mysql_ENTRY_END_HOUR = $mysql_ENTRY_SHIFT_CUSTOM_END_HOUR;
				$mysql_ENTRY_END_MINUTE = "01";
				if ($JUMP_FROM_REPORT_0 == 'YES') {
					$mysql_ENTRY_END_HOUR_MINUTE_COMBO = $mysql_ENTRY_END_HOUR;
				} else {
					$mysql_ENTRY_END_HOUR_MINUTE_COMBO = $mysql_ENTRY_END_HOUR.":".$mysql_ENTRY_END_MINUTE;
				}
			} else {
				$mysql_ENTRY_SHIFT_CUSTOM_END_HOUR = "";
				$seer_HMIACTION_FAULT = 1;
				$seer_FAULT_TYPE = $multilang_WARRIOR_80;
			}
			$WARRIOR_TITLE_REPORT_SHIFT_ID = $multilang_WARRIOR_76." ... ".$mysql_ENTRY_START_HOUR_MINUTE_COMBO." - ".$mysql_ENTRY_END_HOUR_MINUTE_COMBO;
		} else {
			if ($mysql_ENTRY_SHIFT == 88888) {
				$mysql_ENTRY_START_HOUR = "00";
				$mysql_ENTRY_START_MINUTE = "00";
				$mysql_ENTRY_START_HOUR_MINUTE_COMBO = $mysql_ENTRY_START_HOUR.":".$mysql_ENTRY_START_MINUTE;
				$mysql_ENTRY_END_HOUR = "24";
				$mysql_ENTRY_END_MINUTE = "00";
				$mysql_ENTRY_END_HOUR_MINUTE_COMBO = $mysql_ENTRY_END_HOUR.":".$mysql_ENTRY_END_MINUTE;
				$WARRIOR_TITLE_REPORT_SHIFT_ID = $multilang_WARRIOR_77."; ".$mysql_ENTRY_START_HOUR_MINUTE_COMBO." -- ".$mysql_ENTRY_END_HOUR_MINUTE_COMBO;
			} else {
			/* USE PREDEFINED SHIFTS */
				$mysql_ENTRY_START_HOUR_MINUTE_COMBO = $WARRIOR_SHIFT[$mysql_ENTRY_SHIFT]['START'];
				$mysql_ENTRY_END_HOUR_MINUTE_COMBO = $WARRIOR_SHIFT[$mysql_ENTRY_SHIFT]['END'];
				$WARRIOR_TITLE_REPORT_SHIFT_ID = $WARRIOR_SHIFT_NAME[$mysql_ENTRY_SHIFT]."; ".$mysql_ENTRY_START_HOUR_MINUTE_COMBO." -- ".$mysql_ENTRY_END_HOUR_MINUTE_COMBO;
			}
		}
	} else {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_TANKMODEL_75;
	}
	if ($mysql_ENTRY_START_HOUR_MINUTE_COMBO == $mysql_ENTRY_END_HOUR_MINUTE_COMBO) {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_WARRIOR_89;
	} else {
		/* pass */
	}
	if ( $_POST[mysql_ENTRY_START_YEAR] != '' ) {
		$mysql_ENTRY_START_YEAR = $_POST['mysql_ENTRY_START_YEAR'];
	} else {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_FAULT_2;
	}
	if ( $_POST[mysql_ENTRY_START_MONTH] != '' ) {
		$mysql_ENTRY_START_MONTH = $_POST['mysql_ENTRY_START_MONTH'];
	} else {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_FAULT_3;
	}
	if ( $_POST[mysql_ENTRY_START_DAY] != '' ) {
		$mysql_ENTRY_START_DAY = $_POST['mysql_ENTRY_START_DAY'];
	} else {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_FAULT_4;
	}
	if ( $_POST[mysql_ENTRY_END_MONTH] != '' ) {
		$mysql_ENTRY_END_MONTH = $_POST['mysql_ENTRY_END_MONTH'];
	} else {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_FAULT_8;
	}
	if ( $_POST[mysql_ENTRY_END_DAY] != '' ) {
		$mysql_ENTRY_END_DAY = $_POST['mysql_ENTRY_END_DAY'];
	} else {
		$seer_HMIACTION_FAULT = 1;
		$seer_FAULT_TYPE = $multilang_FAULT_9;
	}
	if ($request_detail_level == 'YES') {
		if ( $_POST[mysql_DETAIL_LEVEL] != '' ) {
			$mysql_DETAIL_LEVEL = $_POST['mysql_DETAIL_LEVEL'];
		} else {
			$seer_DETAIL_LEVEL = "LOW";
		}
	} else {
		/* pass */
	}

	/* PREPARE THE QUERY DATE RANGE */
	if ($JUMP_FROM_REPORT_0 == 'YES') {
		if ( $_POST[mysql_ENTRY_END_YEAR] != '' ) {
			$mysql_ENTRY_END_YEAR = $_POST['mysql_ENTRY_END_YEAR'];
		} else {
			$seer_HMIACTION_FAULT = 1;
			$seer_FAULT_TYPE = $multilang_FAULT_2;
		}
		if ($_POST[mysql_ENTRY_MACHINENAME] != '') {
			$mysql_ENTRY_MACHINENAME = $_POST['mysql_ENTRY_MACHINENAME'];
		} else {
			$seer_HMIACTION_FAULT = 1;
			$seer_FAULT_TYPE = $multilang_FAULT_35;
		}
		if ($_POST[mysql_ENTRY_RUN_IDENTIFICATION] != '') {
			$mysql_ENTRY_RUN_IDENTIFICATION = $_POST['mysql_ENTRY_RUN_IDENTIFICATION'];
		} else {
			$seer_HMIACTION_FAULT = 1;
			$seer_FAULT_TYPE = $multilang_FAULT_35;
		}
		$mysql_query_START_DATESTAMP = $mysql_ENTRY_START_YEAR."_".$mysql_ENTRY_START_MONTH.$mysql_ENTRY_START_DAY."_".$mysql_ENTRY_START_HOUR_MINUTE_COMBO;
		$mysql_query_END_DATESTAMP = $mysql_ENTRY_END_YEAR."_".$mysql_ENTRY_END_MONTH.$mysql_ENTRY_END_DAY."_".$mysql_ENTRY_END_HOUR_MINUTE_COMBO;
		if ($mysql_ENTRY_SHIFT == 99999) {
			$WARRIOR_TITLE_REPORT_SHIFT_ID = $multilang_WARRIOR_76." ... ".$mysql_query_START_DATESTAMP." -- ".$mysql_query_END_DATESTAMP;
		} else {
			/* pass */
		}
	} else {
		$mysql_query_START_DATESTAMP = $mysql_ENTRY_START_YEAR."_".$mysql_ENTRY_START_MONTH.$mysql_ENTRY_START_DAY."_00:00:00";
		$mysql_query_END_DATESTAMP = datestampAddTime($mysql_query_START_DATESTAMP, 0, $mysql_ENTRY_END_MONTH, $mysql_ENTRY_END_DAY, 0, 0);
	}

}

?>
