<?php

/*
S.E.E.R.
---------------------------------------------------------------------
System and Environment Effective Reports
-- version 2, codename: Brahma Bull
     ________________
   `/    \-'  '-/    \`
          \    /
          (\||/)

---------------------------------------------------------------------
 ... the http / web based front-end of mod_openopc, providing
     live HMI / reporting / and history functionality.
---------------------------------------------------------------------
---------------------------------------------------------------------
COPYRIGHT

 THE FOLLOWING 18 LINES MAY NOT BE REMOVED, but may be
     appended with additional contributor info.
 SEER 2
 Copyright (C) 2008 - 2013
 V. Spinelli for Sorrento Lactalis American Group
 Copyright (C) 2013 - 2014
 V. Spinelli for SpinelliCreations
 Copyright (C) 2014
 V. Spinelli for Harper International, Corp.
 Copyright (C) 2016
 V. Spinelli and J. Trembley for RS Automation, LLC.
 This program comes with ABSOLUTELY NO WARRANTY;
 As this program is based on [and has dependancies]
 the content of GPL and LGPL works, GPL is preserved (AGPL)
 This is open software, released under GNU AGPL v3,
 and you are welcome to redistribute it, with this
 tag in tact.
 A copy of the AGPL should be included with this work.
 If you did not receive a copy, see...
 http://www.gnu.org/licenses/agpl-3.0.txt
---------------------------------------------------------------------
---------------------------------------------------------------------
CONTACT		
		Author			V. Spinelli
				Email:	Vince@SpinelliCreations.com
				Site:	http://spinellicreations.com
				Handle:	PoweredByDodgeV8

		Copyright Holder	Sorrento Lactalis American Group
				Email:	http://www.sorrentocheese.com/about/contact.html
				Site:	http://www.sorrentolactalis.com

					SpinelliCreations
				Email:	Admin@SpinelliCreations.com
				Site:	http://www.spinellicreations.com

					Harper International, Corp.
				Email:	info@harperintl.com
				Site:	http://www.harperintl.com
					
					RS Automation, LLC.
				Email:	RickS@rsautomation.net
				Site:	http://www.rsautomation.net
---------------------------------------------------------------------
TANKMODEL ADVANCED LOCAL-COMMON FILE
--  EDIT AT YOUR OWN RISK
---------------------------------------------------------------------
*/

	/* FILE SYSTEM NOTE */
	/* ---------------- */
	/* NOTE
	With regard to directory structure for UNIX versus WIN systems,
	S.E.E.R.'s implementation in PHP is operating system agnostic.
	Whether on WIN or UNIX, the syntax is the same.  For example...
	-- PHP call to folder... /my_folder/cheese
	-- will reference WIN folder... C:\my_folder\cheese
	-- will reference UNIX folder... /my_folder/cheese
	We rock the party that rocks the party.
	*/

/* ADDITIONAL CONFIG DATA NEEDED TO RUN */
/* 	-- YOU SHOULDN'T NEED TO EDIT THIS AT ALL */
/* ------------------------------------------------------------------ */

/* --- WARNING -- -- -- WARNING -- -- -- WARNING -- -- -- WARNING --- */
/* --- WARNING -- -- -- WARNING -- -- -- WARNING -- -- -- WARNING --- */
/*								      */
/*	YOU SHOULD -NOT- HAVE TO EDIT THE FOLLOWING OPTIONS	      */
/*	-- THEY ARE HERE FOR SEVERAL REASONS:			      */
/*								      */
/*		1- FUTURE COMPATABILITY				      */
/*		2- EASE OF PROGRAMMING (LOGICAL PLACE TO PUT THEM     */
/*		   TO ALLOW CALL)				      */
/*		3- IN CASE YOU WANT TO START MODIFYING SEER,          */
/*	           AT WHICH TIME YOU MAY NEED TO CHANGE THESE ITEMS   */
/*								      */
/*	-- OTHER THAN THAT, DON'T MODIFY THEM!			      */
/*								      */
/* --- WARNING -- -- -- WARNING -- -- -- WARNING -- -- -- WARNING --- */
/* --- WARNING -- -- -- WARNING -- -- -- WARNING -- -- -- WARNING --- */


/* MODIFICATIONS TO LOCALOPTIONS AS NEEDED TO PREP FOR USE BY SEER */
/* ------------------------------------------------------------------ */
/* -- COUNT */
/* -------- */
$TANKMODEL_COUNT_ADJUSTED = $TANKMODEL_COUNT - 1;
/*	-- this offsets by 1 for array construction */
/*	-- do not edit */

/*	FORM FILL FOR ABOVE */
/*	------------------- */
$TANKMODEL_FORMFILL_NAME = "";
$TANKMODEL_COUNT_CYCLE = 0;
while ( $TANKMODEL_COUNT_CYCLE <= $TANKMODEL_COUNT_ADJUSTED ) {
	$TANKMODEL_FORMFILL_NAME = $TANKMODEL_FORMFILL_NAME."<OPTION VALUE='".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE]."'>".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE];
	$TANKMODEL_COUNT_CYCLE = $TANKMODEL_COUNT_CYCLE + 1;
}

/* -- PRODUCT ID */
/* ------------- */
/*	FORM FILL FOR ABOVE */
/*	------------------- */
$TANKMODEL_FORMFILL_PLC_LEAF_PRODUCT = "";
$TANKMODEL_COUNT_CYCLE = 0;
while ( $TANKMODEL_COUNT_CYCLE <= $TANKMODEL_COUNT_ADJUSTED ) {
	$TANKMODEL_FORMFILL_PLC_LEAF_PRODUCT = $TANKMODEL_FORMFILL_PLC_LEAF_PRODUCT."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_PRODUCT[$TANKMODEL_COUNT_CYCLE]."'>".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE];
	$TANKMODEL_COUNT_CYCLE = $TANKMODEL_COUNT_CYCLE + 1;
}

/* -- PRODUCT DENSITY */
/* ------------------ */
/*	FORM FILL FOR ABOVE */
/*	------------------- */
$TANKMODEL_FORMFILL_PLC_LEAF_DENSITY = "";
$TANKMODEL_COUNT_CYCLE = 0;
while ( $TANKMODEL_COUNT_CYCLE <= $TANKMODEL_COUNT_ADJUSTED ) {
	$TANKMODEL_FORMFILL_PLC_LEAF_DENSITY = $TANKMODEL_FORMFILL_PLC_LEAF_DENSITY."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_DENSITY[$TANKMODEL_COUNT_CYCLE]."'>".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE];
	$TANKMODEL_COUNT_CYCLE = $TANKMODEL_COUNT_CYCLE + 1;
}

/* -- AGITATION CONTROL */
/* -------------------- */
if ( $TANKMODEL_UTILIZE_AGITATOR_CONTROL == "YES" ) {

	/*	FORM FILL FOR ABOVE */
	/*	------------------- */
	$TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_SPEED_ON_LEVEL = "";
	$TANKMODEL_COUNT_CYCLE = 0;
	while ( $TANKMODEL_COUNT_CYCLE <= $TANKMODEL_COUNT_ADJUSTED ) {
		if ( $TANKMODEL_PLC_LEAF_AGITATOR_SPEED_ON_LEVEL[$TANKMODEL_COUNT_CYCLE] != 'NONE' ) {
			$TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_SPEED_ON_LEVEL = $TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_SPEED_ON_LEVEL."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_AGITATOR_SPEED_ON_LEVEL[$TANKMODEL_COUNT_CYCLE]."'>".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE];
		} else {
			/* pass on it */
		}
		$TANKMODEL_COUNT_CYCLE = $TANKMODEL_COUNT_CYCLE + 1;
	}

	/*	FORM FILL FOR ABOVE */
	/*	------------------- */
	$TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_SPEED_OFF_LEVEL = "";
	$TANKMODEL_COUNT_CYCLE = 0;
	while ( $TANKMODEL_COUNT_CYCLE <= $TANKMODEL_COUNT_ADJUSTED ) {
		if ( $TANKMODEL_PLC_LEAF_AGITATOR_SPEED_OFF_LEVEL[$TANKMODEL_COUNT_CYCLE] != 'NONE' ) {
			$TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_SPEED_OFF_LEVEL = $TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_SPEED_OFF_LEVEL."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_AGITATOR_SPEED_OFF_LEVEL[$TANKMODEL_COUNT_CYCLE]."'>".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE];
		} else {
			/* pass on it */
		}
		$TANKMODEL_COUNT_CYCLE = $TANKMODEL_COUNT_CYCLE + 1;
	}

	/* AGITATOR GROUP 1 */
	/* ---------------- */
	$TANKMODEL_MEMBERS_AGITATOR_GROUP1_ADJUSTED = $TANKMODEL_MEMBERS_AGITATOR_GROUP1 - 1;
	/*	-- this offsets by 1 for array construction */
	/*	-- do not edit */

	/* 	FORM FILL AGITATOR GROUP 1 */
	/* 	-------------------------------- */
	$TANKMODEL_FORMFILL_NAME_MEMBERS_AGITATOR_GROUP1 = "";
	$TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE = 0;
	while ( $TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE <= $TANKMODEL_MEMBERS_AGITATOR_GROUP1_ADJUSTED ) {
		$KEY = $TANKMODEL_AGITATOR_GROUP1[$TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE];
		$TANKMODEL_FORMFILL_NAME_MEMBERS_AGITATOR_GROUP1 = $TANKMODEL_FORMFILL_NAME_MEMBERS_AGITATOR_GROUP1."<OPTION VALUE='".$TANKMODEL_NAME[$KEY]."'>".$TANKMODEL_NAME[$KEY];
		$TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE = $TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE + 1;
	}

	$TANKMODEL_FORMFILL_MEMBERS_AGITATOR_GROUP1 = "";
	$TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE = 0;
	while ( $TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE <= $TANKMODEL_MEMBERS_AGITATOR_GROUP1_ADJUSTED ) {
		$KEY = $TANKMODEL_AGITATOR_GROUP1[$TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE];
		$TANKMODEL_FORMFILL_MEMBERS_AGITATOR_GROUP1 = $TANKMODEL_FORMFILL_MEMBERS_AGITATOR_GROUP1."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_AGITATOR_STATE[$KEY]."'>".$TANKMODEL_NAME[$KEY];
		$TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE = $TANKMODEL_MEMBERS_AGITATOR_GROUP1_CYCLE + 1;
	}

	/* FORMFILL FOR AGITATOR BUILTIN HTTP SERVER */
	/* ----------------------------------------- */
	$TANKMODEL_FORMFILL_AGITATOR_BUILTINHTTP_GROUP1 = "";
	$TANKMODEL_AGITATOR_BUILTINHTTP_GROUP1_CYCLE = 0;
	while ( $TANKMODEL_AGITATOR_BUILTINHTTP_GROUP1_CYCLE <= $TANKMODEL_MEMBERS_AGITATOR_GROUP1_ADJUSTED ) {
		$KEY = $TANKMODEL_AGITATOR_GROUP1[$TANKMODEL_AGITATOR_BUILTINHTTP_GROUP1_CYCLE];
		$TANKMODEL_FORMFILL_BUILTINHTTP_AGITATOR_GROUP1 = $TANKMODEL_FORMFILL_AGITATOR_BUILTINHTTP_GROUP1."<OPTION VALUE='".$TANKMODEL_AGITATOR_BUILTINHTTP_GROUP1[$KEY]."'>".$TANKMODEL_NAME[$KEY];
		$TANKMODEL_AGITATOR_BUILTINHTTP_GROUP1_CYCLE = $TANKMODEL_AGITATOR_BUILTINHTTP_GROUP1_CYCLE + 1;
	}

	$TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_ADJUSTED = $TANKMODEL_AGITATOR_STATE_GROUP1_COUNT - 1;
	/*	-- this offsets by 1 for array construction */
	/*	-- do not edit */

	/* 	FORM FILL AGITATOR STATE GROUP 1 */
	/* 	-------------------------------- */
	$TANKMODEL_FORMFILL_AGITATOR_STATE_GROUP1 = "";
	$TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_CYCLE = 0;
	while ( $TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_CYCLE <= $TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_ADJUSTED ) {
		$TANKMODEL_FORMFILL_AGITATOR_STATE_GROUP1 = $TANKMODEL_FORMFILL_AGITATOR_STATE_GROUP1."<OPTION VALUE='".$TANKMODEL_AGITATOR_STATE_GROUP1_LOGIC[$TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_CYCLE]."'>".$TANKMODEL_AGITATOR_STATE_GROUP1[$TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_CYCLE];
		$TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_CYCLE = $TANKMODEL_AGITATOR_STATE_GROUP1_COUNT_CYCLE + 1;
	}
	
	/* 	FORM FILL AGITATOR SELECT SPEED */
	/* 	------------------------------- */
	$TANKMODEL_FORMFILL_AGITATOR_SELECT_SPEED = "";
	$TANKMODEL_AGITATOR_SPEED_COUNT_CYCLE = $TANKMODEL_AGITATOR_SPEED_MIN;
	while ( $TANKMODEL_AGITATOR_SPEED_COUNT_CYCLE <= $TANKMODEL_AGITATOR_SPEED_MAX ) {
		$TANKMODEL_FORMFILL_AGITATOR_SELECT_SPEED = $TANKMODEL_FORMFILL_AGITATOR_SELECT_SPEED."<OPTION VALUE='".$TANKMODEL_AGITATOR_SPEED_COUNT_CYCLE."'>".$TANKMODEL_AGITATOR_SPEED_COUNT_CYCLE;
		$TANKMODEL_AGITATOR_SPEED_COUNT_CYCLE = $TANKMODEL_AGITATOR_SPEED_COUNT_CYCLE + 1;
	}

	/* FORM FILL FOR LEVEL ON */
	/* ---------------------- */
	$TANKMODEL_FORMFILL_AGITATOR_ON_LEVEL = "";
	$TANKMODEL_AGITATOR_ON_LEVEL_COUNT_CYCLE = $TANKMODEL_AGITATOR_ON_LEVEL_MIN;
	while ( $TANKMODEL_AGITATOR_ON_LEVEL_COUNT_CYCLE <= $TANKMODEL_AGITATOR_ON_LEVEL_MAX ) {
		$TANKMODEL_FORMFILL_AGITATOR_ON_LEVEL = $TANKMODEL_FORMFILL_AGITATOR_ON_LEVEL."<OPTION VALUE='".$TANKMODEL_AGITATOR_ON_LEVEL_COUNT_CYCLE."'>".$TANKMODEL_AGITATOR_ON_LEVEL_COUNT_CYCLE;
		$TANKMODEL_AGITATOR_ON_LEVEL_COUNT_CYCLE = $TANKMODEL_AGITATOR_ON_LEVEL_COUNT_CYCLE + 1;
	}

	/* FORM FILL FOR LEVEL OFF */
	/* ----------------------- */
	$TANKMODEL_FORMFILL_AGITATOR_OFF_LEVEL = "";
	$TANKMODEL_AGITATOR_OFF_LEVEL_COUNT_CYCLE = $TANKMODEL_AGITATOR_OFF_LEVEL_MIN;
	while ( $TANKMODEL_AGITATOR_OFF_LEVEL_COUNT_CYCLE <= $TANKMODEL_AGITATOR_OFF_LEVEL_MAX ) {
		$TANKMODEL_FORMFILL_AGITATOR_OFF_LEVEL = $TANKMODEL_FORMFILL_AGITATOR_OFF_LEVEL."<OPTION VALUE='".$TANKMODEL_AGITATOR_OFF_LEVEL_COUNT_CYCLE."'>".$TANKMODEL_AGITATOR_OFF_LEVEL_COUNT_CYCLE;
		$TANKMODEL_AGITATOR_OFF_LEVEL_COUNT_CYCLE = $TANKMODEL_AGITATOR_OFF_LEVEL_COUNT_CYCLE + 1;
	}

	/* PRESET SPEEDS FOR AGITATORS */
	/* --------------------------- */
	$TANKMODEL_AGITATOR_PRESET_SPEED_COUNT = $TANKMODEL_AGITATOR_PRESET_SPEED_SETTINGS_PER_PRESET * $TANKMODEL_AGITATOR_PRESET_SPEED_PRESET_COUNT;;
	$TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_ADJUSTED = $TANKMODEL_AGITATOR_PRESET_SPEED_COUNT - 1;
	$TANKMODEL_AGITATOR_PRESET_SPEED_PRESET_COUNT_ADJUSTED = $TANKMODEL_AGITATOR_PRESET_SPEED_PRESET_COUNT - 1;
	/*	-- this offsets by 1 for array construction */
	/*	-- do not edit */
	
	/*	FORM FILL PRESET SPEED LEAF */
	/*	--------------------------- */
	$TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_PRESET_SPEED = "";
	$TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_CYCLE = 0;
	while ( $TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_CYCLE <= $TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_ADJUSTED ) {
		$TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_PRESET_SPEED = $TANKMODEL_FORMFILL_PLC_LEAF_AGITATOR_PRESET_SPEED."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_AGITATOR_PRESET_SPEED[$TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_CYCLE]."'>".$TANKMODEL_AGITATOR_PRESET_SPEED_NAME[$TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_CYCLE];
		$TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_CYCLE = $TANKMODEL_AGITATOR_PRESET_SPEED_COUNT_CYCLE + 1;
	}

} else {
	/* continue */
}

/* -- LOCKDOWN DUE TO LACK OF CLEANING */
/* ----------------------------------- */
if ( $TANKMODEL_UTILIZE_LOCKDOWN_CLEANING == "YES" ) {
	/*	FORM FILL FOR ABOVE */
	/*	------------------- */
	$TANKMODEL_FORMFILL_PLC_LEAF_RELEASE_LOCKDOWN_CLEANING = "";
	$TANKMODEL_COUNT_CYCLE = 0;
	while ( $TANKMODEL_COUNT_CYCLE <= $TANKMODEL_COUNT_ADJUSTED ) {
		$TANKMODEL_FORMFILL_PLC_LEAF_RELEASE_LOCKDOWN_CLEANING = $TANKMODEL_FORMFILL_PLC_LEAF_RELEASE_LOCKDOWN_CLEANING."<OPTION VALUE='".$TANKMODEL_PLC_LEAF_RELEASE_LOCKDOWN_CLEANING[$TANKMODEL_COUNT_CYCLE]."'>".$TANKMODEL_NAME[$TANKMODEL_COUNT_CYCLE];
		$TANKMODEL_COUNT_CYCLE = $TANKMODEL_COUNT_CYCLE + 1;
	}

	/*	LOGIC TO RELEAE FROM LOCKDOWN CLEANING */
	/*	-------------------------------------- */
	$TANKMODEL_FORMFILL_RELEASE_LOCKDOWN_CLEANING_LOGIC = "<OPTION VALUE='".$TANKMODEL_RELEASE_LOCKDOWN_CLEANING_LOGIC."'>Release Lockdown";
	/*	-- plc logic value to write in order to release lockdown */

} else {
	/* pass */
}

/* -- ALARMS */
/* --------- */
$TANKMODEL_ALARM_COUNT_ADJUSTED = $TANKMODEL_ALARM_COUNT - 1;
/*	-- this offsets by 1 for array construction */
/*	-- do not edit */

/*	FORM FILL FOR ABOVE */
/*	------------------- */
$TANKMODEL_FORMFILL_ALARM = "";
$TANKMODEL_ALARM_COUNT_CYCLE = 1;
while ( $TANKMODEL_ALARM_COUNT_CYCLE <= $TANKMODEL_ALARM_COUNT_ADJUSTED ) {
	$TANKMODEL_FORMFILL_ALARM = $TANKMODEL_FORMFILL_ALARM."<OPTION VALUE='".$TANKMODEL_ALARM_COUNT_CYCLE."'>".$TANKMODEL_ALARM[$TANKMODEL_ALARM_COUNT_CYCLE];
	$TANKMODEL_ALARM_COUNT_CYCLE = $TANKMODEL_ALARM_COUNT_CYCLE + 1;
}

/* -- PRODUCT STORED IN TANKS */
/* -------------------------- */
/*	FORM FILL FOR ABOVE */
/*	------------------- */
$TANKMODEL_FORMFILL_PRODUCT = "";
$TANKMODEL_PRODUCT_COUNT_CYCLE = 0;
while ( $TANKMODEL_PRODUCT_COUNT_CYCLE <= $TANKMODEL_PRODUCT_COUNT_ADJUSTED ) {
	$TANKMODEL_PRODUCT_NAME_forOrder[$TANKMODEL_PRODUCT_COUNT_CYCLE] = $TANKMODEL_PRODUCT[$TANKMODEL_PRODUCT_COUNT_CYCLE];
	$TANKMODEL_PRODUCT_ID_forOrder[$TANKMODEL_PRODUCT_COUNT_CYCLE] = $TANKMODEL_PRODUCT_COUNT_CYCLE;
	$TANKMODEL_PRODUCT_COUNT_CYCLE = $TANKMODEL_PRODUCT_COUNT_CYCLE + 1;
}
if ($TANKMODEL_COUNT > 0) {
	array_multisort($TANKMODEL_PRODUCT_NAME_forOrder, $TANKMODEL_PRODUCT_ID_forOrder);
} else {
	/* pass */
}
$TANKMODEL_PRODUCT_COUNT_CYCLE = 0;
while ( $TANKMODEL_PRODUCT_COUNT_CYCLE <= $TANKMODEL_PRODUCT_COUNT_ADJUSTED ) {
	$TANKMODEL_PRODUCT_LOGIC[$TANKMODEL_PRODUCT_COUNT_CYCLE] = $TANKMODEL_PRODUCT_ID_forOrder[$TANKMODEL_PRODUCT_COUNT_CYCLE];
	/*	-- compatability fix due to upgrading basecode */
	/*	-- there used to be a PRODUCT_LOGIC array, and there no longer is */
	$TANKMODEL_FORMFILL_PRODUCT = $TANKMODEL_FORMFILL_PRODUCT."<OPTION VALUE='".$TANKMODEL_PRODUCT_LOGIC[$TANKMODEL_PRODUCT_COUNT_CYCLE]."'>".$TANKMODEL_PRODUCT_NAME_forOrder[$TANKMODEL_PRODUCT_COUNT_CYCLE];
	$TANKMODEL_PRODUCT_COUNT_CYCLE = $TANKMODEL_PRODUCT_COUNT_CYCLE + 1;
}

/* -- TANK STATE */
/* ------------- */
$TANKMODEL_STATE_COUNT_ADJUSTED = $TANKMODEL_STATE_COUNT - 1;
/*	-- this offsets by 1 for array construction */
/*	-- do not edit */

/*	FORM FILL FOR ABOVE */
/*	------------------- */
$TANKMODEL_FORMFILL_STATE = "";
$TANKMODEL_STATE_COUNT_CYCLE = 0;
while ( $TANKMODEL_STATE_COUNT_CYCLE <= $TANKMODEL_STATE_COUNT_ADJUSTED ) {
	$TANKMODEL_STATE_LOGIC[$TANKMODEL_STATE_COUNT_CYCLE] = $TANKMODEL_STATE_COUNT_CYCLE;
	/*	-- compatability fix due to upgrading basecode */
	/*	-- there used to be a STATE_LOGIC array, and there no longer is */
	$TANKMODEL_FORMFILL_STATE = $TANKMODEL_FORMFILL_STATE."<OPTION VALUE='".$TANKMODEL_STATE_LOGIC[$TANKMODEL_STATE_COUNT_CYCLE]."'>".$TANKMODEL_STATE[$TANKMODEL_STATE_COUNT_CYCLE];
	$TANKMODEL_STATE_COUNT_CYCLE = $TANKMODEL_STATE_COUNT_CYCLE + 1;
}

/* -- SOURCES AND DESTINATIONS */
/* --------------------------- */
$TANKMODEL_SOURCE_COUNT_ADJUSTED = $TANKMODEL_SOURCE_COUNT - 1;
/*	-- this offsets by 1 for array construction */
/*	-- do not edit */
$TANKMODEL_DESTINATION_COUNT_ADJUSTED = $TANKMODEL_DESTINATION_COUNT - 1;
/*	-- this offsets by 1 for array construction */
/*	-- do not edit */

?>
